apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app notifiarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      notifiarr:
        containers:
          app:
            image:
              repository: ghcr.io/notifiarr/notifiarr
              tag: v0.9.0
            env:
              TZ: Europe/Copenhagen
              TMPDIR: /tmp
            envFrom:
              - secretRef:
                  name: notifiarr-secret

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 5454

    persistence:
      config:
        existingClaim: *app

      tmp:
        type: emptyDir


