apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex
resources:
  - riven-backend-secret.yaml
  - riven-backend-configmap.yaml  
  - ../../base/riven-backend 

patches:
  - target:
      kind: Deployment
      name: riven-backend
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: plex
    