apiVersion: v1
kind: Secret
metadata:
    name: riven-backend-secret
    namespace: plex
stringData:
    RIVEN_DATABASE_HOST: ENC[AES256_GCM,data:Ep+8SwFMoMLlITbIdEnmLfafy6b90OWRtrGByaQefHeYGsoxXc1AoWH3p3YqtL27Ptlg6IODIThb+DXuvjhOQACem6N6PrQPB6RIRCztco7DEjmMhUgVJOp9ohg=,iv:3BLexq5EcSc6Y+cO1aF727tNQR8upDFSfT7DLaVGUxs=,tag:d1F4xqVNbAvN+2dCn/gGtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-07T16:35:14Z"
    mac: ENC[AES256_GCM,data:O9YrmJjDzedaeQyF5eAGsHbctMcZCo6DpUGVAoK5qiqXE+VQ1/ECp844UQrXSca0ot4q4i4yz7FgD76DXXqg+Nbxi/evf5QyOWGA55XB+cPlZcBEhkq/iXQpi8XMo1rOM6g+VtKWf7mEsW1d+fDZOctxfC0F8QD+vQcTNlGeYnY=,iv:eGN884kwq2bo3qdmSwY90QpipESvL8Vl+qXOu+RIlc8=,tag:xXzfOtqg+DGV1EtCYixzrw==,type:str]
    pgp:
        - created_at: "2025-02-07T16:35:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ifymI7TXLxAQ/+PpEbvK3igZNm6hZRKxH/SJ+DdXqBtaj3hRu9Tfc1VIR7
            Jfndm9nkB6Anfu/3DcTkfrv/R8cQ2HK4ef1phKQ6Z2p4NajBLQDKQHcWIBDn/Vgn
            ldMsgzzC4C12Heq9gV6NWo+mbuNUcoS3hkZwrAGm3P+rTsB9LD11vuuUfHnV7yWQ
            DisQE75B0zs3AJaobGZ0UK3Ud747NZGzCGTb9/hKirvwVLZus9tjSKr1n3XSr/pL
            fvXy/GbrYhsEVSFWV3mllyfb+H1rqmYQaGpSF2iCR8KA79QxiITKURtE1wrcOtBZ
            pz9mdor1qUJqraGEtpbHynB1/ldz9DUIQDhxCgFWbLSVnDT64TX84jvJ3bKX2CRB
            Tbwz5D7XdKdc0FrmBC7wVROmxKs1SbF9aH5LVWtsX1DzQiyEYQMXISjdxG0G8Sp/
            zmvm0Mb+pacRGSbq86YA7jM7uJjIiWk1hB9nJbMIt5wQyUtWc7g72YMJKo/ySpVQ
            N84pOG5h36ADDJHFfy4wQ/1WE4/kNj8tPgdQ92pIalTCjeO/xI5m8TDse27V3efD
            nj69W8PpWWTg9mLZz3ELzYOpgugYkR26IDIbTPoSg/bfYjx6uS7cebA1zBvxH8PL
            ZbAX/yPLBjutTKloxqFNKiyd3vIhNUdNOFQNmFhidPAau9MTzny43KqWGC32d0nS
            XAHa9Q6BxoqNFXiYSmz9yz84xjyuTrvI3jpvjIz0cdDTwUd160aYMH3lt3rratWG
            r89kAkJNv1e6/RFJY6DMY47l6EkBL4G+30yTywE5nQnWlzpkEyJjx0hqpyJ1
            =lmGE
            -----END PGP MESSAGE-----
          fp: E6862079C6D05BFFF38F920C4EB7CEF00A5BE02D
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
