apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app actual-budget
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      actual-budget:
        containers:
          app:
            image:
              repository: ghcr.io/actualbudget/actual-server
              tag: 25.4.0
            env:
              - name: TZ
                value: Europe/Copenhagen
              - name: ACTUAL_PORT
                value: &port 5006

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100

    service:
      app:
        controller: actual-budget
        ports:
          http:
            port: *port

    persistence:
      data:
        existingClaim: *app
