---
apiVersion: v1
kind: Service
metadata:
  name: riven-backend-service
  namespace: riven
  labels:
    app: riven
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: riven
    component: backend