---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: plex
  name: riven-backend-pvc
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi