apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: "1.8.1"
      sourceRef:
        kind: HelmRepository
        name: longhorn
  targetNamespace: longhorn-system
  values:
    defaultSettings:
      defaultDataPath: "/var/lib/longhorn"
      defaultReplicaCount: 1 