---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app home-assistant
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../components/volsync
    - ../../../components/volsync/remote
    - ../../../components/gatus/internal
    - ../../../components/gatus/external
  interval: 1h
  path: ./apps/base/home-assistant
  postBuild:
    substitute:
      APP: *app
      SUBDOMAIN: *app
      CAPACITY: 18Gi
      GATUS_PORT: "8123"
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: &namespace home-assistant
  timeout: 5m
  wait: false