apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:UHu6uw==,iv:PDAH0RlTx/SM4D00RUedAN674Cdgot1HMCGrxZ2tymw=,tag:iKegtKBCxQbEjnavGzhnIw==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:C/GJcycM9DHH7KRWcZt18A==,iv:PZ3bV2sxndq2/PEp1Tr2pcz0wUhVsnO7iREk0tpKFik=,tag:LO6au8LcXjsWvrLFQr60EQ==,type:str]
sops:
    lastmodified: "2025-05-18T19:00:00Z"
    mac: ENC[AES256_GCM,data:tgHZmHpACEEUlIKdr3PCdYIYJgyHyBsunulezv3FC6KWHtdocfZUb2p9AhAjMe6jtVFL64NqVF+PVJJ//kE6vazSyQPx9AFasPdhLPUvokNTXJeO3hjkUlBjT9HFivupOaVMWxtVCvQCsWMv3guQ29CBX8yFmc1jDzZz2K3aeXs=,iv:GGYT9YpgIGhA/v5LoYcG4pXWsuMvpMxrwHlDYZLSZnQ=,tag:40wa8fVfWy5WICE+pXBfEA==,type:str]
    pgp:
        - created_at: "2025-05-18T19:00:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ifymI7TXLxAQ/+K6+Cdjp3jIPXlGeHG2GA0pFx6I3SC23Xdb6LNsV8ZhSf
            VEGENqukeRXQX1Gg1Ib2JueUmdF73IdKczYvr+4QAsDrLTTJ/d/ToFcFx10+fhsQ
            INagZfJTxCxFsM+y+tj0fvy/Re/bsdGBxzyJVJCTk4p15gLm/sB9EOaljvr/B0U5
            T0RUU6AHHCoNbDdCk87AE0i22cfSG+MU5a3nVKaogmYgU4G7NJ2nGa9I+8j0Aw2o
            kJlFJVtJSDCD8u2h9+BVBfqYLQCQPz8IABRa7IUERXnaoWhJJP+mKOheq6xMCHfR
            ZaWBTat8e1ieiOVPMSwjsyXIbtRwSBle2ivYJAJBb5BMAh5eRU8fzSDvearZtx0e
            NNzs6mbyXPF2lOY1GrngAG0bwWO567If0LC85h4vo/08LNr4F3+U0f12v12epMaU
            oYtfCTkUZQVs0WSFwl2t+U0QdfPImhb/aVPdFyEX+QmZ7u+Lb4QL2vHkeBWxKplj
            FeYeXAFum+0t+/mcxn1qUnra/wYNdEyo4SCBzZL/DkSPy2DyallwQrcapPJY5gi3
            l96KGQREzVaoaC0UbgsLYG235afxuPgR5ah6mk5nbWw5IdZo4vkN5H8oRottn8Se
            nrvgTQqs9vGLzZvKWboTyQznKpTQRt28HmQHhGsJK5qDW2ewyFk671BVoV6YgsTS
            XgFFQ//2kyJKmwyGW7k2d4MT9G9S4sWcW5/Fs7Jy/1tXY0zbJGPQ58rrdAov/VBs
            MkTnDiGssBo/wwHnvRKMZFGWrNK6Bn0vtPWm76uCb3ReoDZoaBwExEG6Vs+ZZeA=
            =qlqe
            -----END PGP MESSAGE-----
          fp: E6862079C6D05BFFF38F920C4EB7CEF00A5BE02D
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
