apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app isponsorblocktv
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      isponsorblocktv:
        containers:
          app:
            securityContext:
              allowPrivilegeEscalation: false
            image:
              repository: ghcr.io/dmunozv04/isponsorblocktv
              tag: v2.6.1
            env:
              TZ: Europe/Copenhagen

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    persistence:
      config-file:
        type: secret
        name: isponsorblocktv-secret
        globalMounts:
          - path: /app/data/config.json
            subPath: config.json
            readOnly: true