apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: vaultwarden
stringData:
    VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:GNMEwGF21nYzB/IbtKUGdJOd+CaOy7qCakZj5g9r+RbeL+wlwNaCbTnMJJM=,iv:5TRlWe1FsjjscBHWDqoDt9mLuVUpZ0tmJdi7r5KwWF4=,tag:2NZongYQn2XrgDEvtc0Adw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T18:35:15Z"
    mac: ENC[AES256_GCM,data:QXb05soHJEyXoO4kCSsDq2SzhKlGMYxlRRe8FfRWz1xxg8e01lbnZGHyMMGg8IE2f6nH5vFg4pwh7h3jDrlzKkqckX+bir56GnJRLk3kqDO2F+vNNak0D7ilmB6xjWRE8onPKcAMO8Q/PL94t7a9p98Px4L31zB8gNJivnd9fx4=,iv:pGqSWSZhfmHoqyDB2+bxaCzFH7RskxmufH8AaVgdFUI=,tag:Wl5loMd8w/w1HpS3JN2TwA==,type:str]
    pgp:
        - created_at: "2026-07-18T18:35:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ifymI7TXLxAQ//akhoyLZHeOwOvXny8lfKEzSAvlmNkemrKV8W0q1r5ZZn
            gwlFhA2vQps67PmDtX026IP3X8e1RjjS7uY94W/Fj9h2JInTtOmYt1647h94A1qP
            UyeIG4JOyNAhqIo6Ekfj0FZmRZAWcpLmczciCDIca8xVcEfAMKwrRpP5XBbi5lap
            V37BUwhpJ7N2xDr5r82hEhiHPpJllwnIMEKQL9VqJfMqd2X3Pd2HOyslMd3MoJA1
            yEeV7sY1vVTaeHrKP2Q9ErE+gHPYzoumceRS9/uMK7Xuyb7zDxgb7ILnqRgY1QoU
            FuOeJyenGBnKDEscKVOcDqKI4E4mBr6W+VUcvS6G5yYO26WBYtE3V3vUXziuRk5L
            kq3gF0pyEzKVd9IL2QjEzn75XaYNG6lMLei8rsQJINT2UvdPGRXqwsaN88LP1VAX
            3EWuj8PiTECnM5YbwVCoRXVmasT7ZDMA9cADnGoMfi6k7cQ6seK4f9Sfceyb5eWf
            mHlVlQ+BcDqKqEzjMEgS2/vdqK74YCGzwkLkw7YmJk/zXYW1aodZ0BwinGCj6zJK
            t8HV0xWBr5XYm0S2nERymJUdoWMkUoG9KS/AES1llK+gIZUft3T9TZIaAWCG2ZiG
            LL8aKasU1qZK52HtxsM5jRkgMWUWmNjeF+fTdvgjOtXGnyMsNbC6189RyRkdccbS
            XgFJiAw2Ta1PeR0DAY9dqQQuPOJwbeoq/SP9FjxAwo1zzlt/EnUcWzIrXS9gP/x9
            1Z0bxFrbq7YqYzmsiEuP92Bz8zBCUsgRxQR1RqQoHNaqoEF7x5R/MG8VLNIiTZI=
            =if4v
            -----END PGP MESSAGE-----
          fp: E6862079C6D05BFFF38F920C4EB7CEF00A5BE02D
    version: 3.13.2
