apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app zigbee2mqtt
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      zigbee2mqtt:
        containers:
          app:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 2.2.1
            env:
              TZ: Europe/Copenhagen
              ZIGBEE2MQTT_DATA: /config

              ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
              ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: 'false'
              ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: 'false'

              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: debug
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'

              ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: 60
              ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: 2000

              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: 'false'
              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"

              ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API: "true"

              ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: &http_port 8000
              ZIGBEE2MQTT_CONFIG_FRONTEND_URL: "https://${SUBDOMAIN}.hephaestus.markmk.com"
              
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED: "false"
              
              ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
              ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: 60
              ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: "true"
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto.mosquitto.svc.cluster.local
              ZIGBEE2MQTT_CONFIG_MQTT_VERSION: 5
              
              ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"

              ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE: 115200
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: &hostPath /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_cc27ec094470ec119067213519c2d21c-if00-port0
              ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: ember
    service:
      app:
        controller: zigbee2mqtt
        ports:
          http:
            port: &port 80

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        
      nodeSelector:
        feature.node.kubernetes.io/sonoff_zigbee: "true"

    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /config

      zigbee:
        type: hostPath
        hostPath: *hostPath
        hostPathType: CharDevice
        globalMounts:
          - path: *hostPath