---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-homepage
  namespace: homepage
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: homepage
          port: 3000
          namespace: homepage
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-homepage
  namespace: homepage
spec:
  stripPrefix:
    prefixes:
      - "/homepage"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-homepage-strip
  namespace: homepage
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/homepage`)
      kind: Rule
      middlewares:
        - name: strip-homepage      
      services:
        - name: homepage
          port: 3000
          namespace: homepage                    