apiVersion: v1
kind: ConfigMap
metadata:
  name: riven-frontend-configmap
data:
  PUID: "1000"
  PGID: "1000"
  TZ: Europe/Copenhagen
  BACKEND_URL: "http://riven-backend-service.media.svc.cluster.local:8080"