apiVersion: v1
kind: Secret
metadata:
    name: riven-postgres-secret
    namespace: media
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:/aVnvEm4qas=,iv:nwm/ltw1ibIO3HLmcQgN/DPdvJPm97gGevAM1ZSSjYQ=,tag:XKpy/hfUPmIYCV6MU0Em8g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tgfB1Rh4jCfL/g==,iv:9T9bXvQIx2u4iSuVXRMkvZxJbfgzvADA3WszQg7zlmg=,tag:ZMQbb/SUuZQULnCM8/Ekhg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Y+40ZNQ=,iv:anmi1r46LuTkswUYBzgJzgaHqOsI06P2dDvbORlUuhQ=,tag:/MAL1D4BjwVoyH0aMsznEA==,type:str]
sops:
    lastmodified: "2025-05-03T18:01:45Z"
    mac: ENC[AES256_GCM,data:667vMl1f57uv998w/UsnJXpIwpeq0TqWm01+0r5iSL+Hh6Ir+mtV7yvai+NtHADKNYQucOAzuB3PGjuyrmbf3aLv6N+4hty3aPLzbXVD7amSAopFNOhNPaeHgvMSBB0ocsttbr4pYWntD8jt6LAXkIWraAq6nQufST+Am+QvEmE=,iv:FqucVfVAS13yn4Ad8qpAxkUbe/cwobI3a1ione4gBWk=,tag:4rh5Qk/I9FMbrQpVWaLP+w==,type:str]
    pgp:
        - created_at: "2025-05-03T18:01:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ifymI7TXLxAQ/9FkKGOuWKQKsF3tJm2xLUZwVoI4PxfBEb5N7rqgEZIxpe
            7Z4zZtSjPd/kO2hWLIJomPVw/VN7qJpwPM55UGnFJehJd97EiAnfgYhfYYMeau9J
            kqqPV4QQA2pLu3D4wVb30y9IrvViTad59ve8cZmdClF+ZMx16ldkaiwumWtGtpXI
            TYhNQ2EYKR+e7bW9Oigjh9GL9Fh0ZSX6DG1eEDLrXE/DifXCc6N7wTyDRT/xD59H
            VUDT2lm19GaZbE/xXyfWBZN3u0HCZ++v7QaXdgpWv3JkvD2ZoHsSNfGa4QxNDIea
            DYCGCjhq36WccLV+gXgPbjfDiX8mDJjcQYaW4S9v3Sk4dnqTiRJmSmG/stjErh1W
            kd2sm5yiNvoM0Qb6+IAAXwznBTlWxx2elEMmezz0FwCnzsqqDeUMAU01TzFNZmZ5
            DQdeN0p6ydAniCw/pIFxJxIC+T83uFB5exxNyE8PhzI7MgLMPA60ZJs/rq/uiX+O
            HngN5K9k6L+HwUE6GCl8y6tRbx7UjolP43iFkjN+JFxgQskglE5027j1uhXpanr8
            Y+2fUVJC+giT4e9+4KsSlWPbSkytr6WDobYER0QUmwwJm2nv68gwdLvMKfbmGvQP
            0+2FUTQYL0YXxttOb5hdWHHdzxz8uTBxMIbvYZRnRhky5bU7zVqIPYmFtxZc38bS
            XAE5sccg/tosCTRa2MPWuhYtgAdCkLNzGbNJuWyqKST1/YKtyd4qQMM62oGVmun/
            vDpUVqTeX2R0pMFimP374wOVWTnbjd/kSg6J/0ZmP7MXScvx0vw7urwZ6cDQ
            =yRoG
            -----END PGP MESSAGE-----
          fp: E6862079C6D05BFFF38F920C4EB7CEF00A5BE02D
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
