apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app riven
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      riven:
        containers:
          frontend:
            image:
              repository: spoked/riven-frontend
              tag: v0.20.0
            env:
              - name: TZ
                value: Europe/Copenhagen
            envFrom:
            - secretRef:
                name: riven-frontend-secret              
            - configMapRef:
                name: riven-frontend-configmap  
            dependsOn: backend                
          backend:
            image:
              repository: spoked/riven
              tag: v0.21.20
            env:
              - name: TZ
                value: Europe/Copenhagen     
            envFrom:
            - secretRef:
                name: riven-backend-secret              
            - configMapRef:
                name: riven-backend-configmap
            dependsOn: postgres  
          postgres:
            image:
              repository: postgres
              tag: 17.0-alpine3.20    
            envFrom:
            - secretRef:
                name: riven-postgres-secret              
            - configMapRef:
                name: riven-postgres-configmap
            probes:
              readiness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command: ["pg_isready", "-U", "postgres"]
                  initialDelaySeconds: 10
                  periodSeconds: 5

    service:
      frontend:
        controller: riven
        type: ClusterIP
        ports:
          http:
            port: &portfrontend 3000
      backend:
        controller: riven
        type: ClusterIP
        ports:
          http:
            port: &portbackend 8080
      postgres:
        controller: riven
        type: ClusterIP
        ports:
          http:
            port: &portpostgres 5432


    persistence:
      data:
        existingClaim: riven-backend-pvc
        advancedMounts:
          riven:          
            backend:
              - path: /riven/data

      rclone:
        type: hostPath
        hostPath: /mnt/zurg/
        globalMounts:
          - path: /mnt/zurg
            readOnly: true

      media:
        existingClaim: shared-media-pvc
        advancedMounts:
          riven:
            backend:
              - path: /mnt/library

      database:
        existingClaim: *app
        advancedMounts:
          riven:
            postgres:
              - path: /var/lib/postgresql/data/pgdata