---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: riven-backend-pvc
  namespace: media
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi           
