apiVersion: v1
kind: Secret
metadata:
    name: riven-frontend-secret
    namespace: media
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:sX0lPDetAOTk4sG731AJXl+NGZ9SOyCVtXedzwyH,iv:/ajU6tbPs5JQY9lqx6n3Bi3uz/ZjsxbJim5BnUNtLAk=,tag:+v9wNwmOeJfBcFu2g74MeA==,type:str]
sops:
    lastmodified: "2025-05-03T17:17:20Z"
    mac: ENC[AES256_GCM,data:OKgvyroQreR12MDKxSEBeSHZk5HF5+licR8HQErZzBxnG+JqDEBYdXC8VtaRqWRg17JZko3j0ZF8EmVVKtH4I8e+i2iCZfsLG+oSrYAj1Q/jgkCkKdoYSqiCXJxk7aHMJKX5pdbauWSgs9WDiookb8Q3HJtNG34q0jc8F5CZc7c=,iv:egCq5xK6IH2sVNDDAtXpaTkWN/FF8qaO7q4rF11LvsE=,tag:kg2mrDcR4XOJXNxhA1trHw==,type:str]
    pgp:
        - created_at: "2025-05-03T17:17:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ifymI7TXLxAQ/6ArCFdxYfxbZ2hzU5u2pCk583jjzDeh/1Cpq4XXgv6993
            0+d+Expbi+kU1hRO7IxIF69Nb5lnHxziX0zATLXhjgKx6o3/qyhB7VIYoNYuhBhn
            VwPxJ+9NmMTo7vy7Zwx5qAcjeN2Lx6v6cmzE9MyGCAmbB39hQebcFfrRGA5Xpab9
            k4NKaGH4s2VLbX5v3G3AzmU08I4mtpFsKZ4puAhtnKHkK2Bi/h0MDRvcPhNIlGYu
            yNklk9UxIxN9KTiwmE9GJlUIhQ/FHtvLkAbWGxRXN5uFMmDrd/H/6Ukx6CwmC97A
            ZOpBjq8qpo9C4Jh84sZLeWLyNqykfM1MEyd7DDqzdZIpMriMKGWlqwmyJD64Yepq
            h+2bDRDhMfJLkYufw2jGSb3XLhx995Wul3DQJ98z9v0k2MAPB0lx7Fo2BCkfBHZv
            4eO3Xbx1oEQVyqgeuUQTzlQESkOpWzDnMnebf4sl0Qo4Lk07+D2XaYTKXbnrFXtZ
            xq26K+I97NEmLR+cB+BpWimWOkJxmUO8nGVtVRCFN+BbPo3bnVrfeBQ/P8gxKpUB
            XOMAmA3QeD+63+Ui9ItUWSsjiZgWCG/PY7CeyG3tuYmLzLBcbH2xSGdRB316LxXI
            SNDYEMH1OHJH6+N4s3gvo8NxqTGu+dMzPKyhcwU+EwKekBetvLmLsOm27ZJdPdPS
            XgFYvJkm2kx1AUf6XGnIvGolIq3zCQoSgmHVrbF381uCjgaA1zW+ltRE5OY7lh9C
            T4Jt0MmD047JaDXLLNKg00YGSNQhau0N0A4LuYboWP/JJfplm+LSQVpC30zcPAc=
            =BBwk
            -----END PGP MESSAGE-----
          fp: E6862079C6D05BFFF38F920C4EB7CEF00A5BE02D
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
