apiVersion: apps/v1
kind: Deployment
metadata:
  name: riven-frontend
  namespace: riven
  labels:
    app: riven
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: riven
      component: frontend
  template:
    metadata:
      labels:
        app: riven
        component: frontend
        app.kubernetes.io/name: riven       
    spec:
      containers:
      - name: riven-frontend
        image: spoked/riven-frontend:latest
        envFrom:
        - secretRef:
            name: riven-frontend-secret              
        - configMapRef:
            name: riven-frontend-configmap
        ports:
        - containerPort: 3000
      restartPolicy: Always