---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: riven
  name: riven-postgres-pvc
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi