apiVersion: v1
kind: Secret
metadata:
    name: riven-backend-secret
    namespace: media
stringData:
    RIVEN_DATABASE_HOST: ENC[AES256_GCM,data:lKHuis2qmE9zrFyPRT0q2y2VmukKfeXdzB9JDxD+,iv:rCMvv83IMcswNGI9Fm/1L8csK8vrTE+WyHPF7YWAEp0=,tag:5KNJpBkHV5rNXibmW1geWw==,type:str]
sops:
    lastmodified: "2025-05-03T17:17:15Z"
    mac: ENC[AES256_GCM,data:sZcjhfs6+uGi4fgmA92Q2hu8PF2FyabaoWeKUpAd3Irq+R3RLZweGIPuvzzpNduw7yq9H1KzpjYqQQWe0qeGxAi/DVwVmDkvsFt1SXhGshvlHFZCSTBVKRN6PZlofAf67v8pyzSaEUshM35jy3MPki38xTe6LrmocJD+Bhy5Hdc=,iv:4SjPxduqe2kHGhS0rrAa3kTF1+T4ITIw6KSq7aVp0Nw=,tag:qvZ9yy5aZ+MqcDqKDXq61A==,type:str]
    pgp:
        - created_at: "2025-05-03T17:17:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ifymI7TXLxAQ/9F+g8n7VIdeg+Blk1veRvHK46hn86MwjZYwhajNgejN1O
            UfNm297Hbo4rVtn8ddO4wCXpKqAP+VZIzgxUO1oPmUDCZfeFDf7u/tfCddUYDZzj
            pDliNIO74WEa9BfW/TD2vimsbt952HbyONyQipN4swggGrtFIF9YqElGAkNCjgRE
            pWuMGKzgxqrLq3kdNgRs0g4M3LnuWcMAFuLSgHkVprg3cl0wCsmxPW6stX4GKAP8
            7eHHamNigosJAYleAKIHEJrKNMsspa86J56BZiVkSu1jygN7zRi4sVyp5u3VBPR2
            X8ymjbmFHWhZ50LPIb5PP758Mj6/nQ+CpSc7CWiXFKKstOEid+H43jPRdUjQko7r
            ki3ExDD9bKgyKn4Im7N6/0/wAV2WOOFwv519mBnmERrZQMWUAKJsA471nEgKC7MC
            be92U4GBhOcxYct2VJkix+upKPMYw5UEG17mxs7W+TIHe0VlDWc9VP4pGT9KASGR
            HKtSAN/KLkjAtNv5PabnjLvLin3JAJ5dcxwzk4yf9ueoyn/qAW8YPOXl9eo1EL8m
            bMLniOaPhdO2E0D44pqxJgRkxobG+wEboXI/JTK/xwviJ75XTGh7FmTEv1MgyAiF
            aYkQSu+i75SRvajQSOyjqLEeQ5ifR01ww0gOHW1JfdgR9ozZV5H6mtGlQg/Yn7DS
            XAEr0LXgJ5hCIrYlngUGdx0Kq9SKLoB6fp6xVQHgCg4Lzh+N5BkcLfK9ZDcY4inn
            rmCOnb7v2UMNfYDXLCJoKlr6pkaiaRzWJdL6vKeBf2AdittfP4zs85+mMm09
            =agph
            -----END PGP MESSAGE-----
          fp: E6862079C6D05BFFF38F920C4EB7CEF00A5BE02D
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
