apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack-namespace.yaml
  - alertmanager-secret.yaml
  - kube-prometheus-stack-ingressroute.yaml
  - kube-prometheus-stack-release.yaml