- name: Install and configure MetalLB
  hosts: master
  tasks:
  - name: Install
    ansible.builtin.shell: |
      kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/main/config/manifests/metallb-native.yaml
    register: res
    changed_when: res.rc != 0

  - name: Copy config file
    ansible.builtin.template:
      src: metallb_config.yml.j2
      dest: /tmp/config.yml
      mode: "0755"

  - name: Configure
    ansible.builtin.shell: kubectl apply -f /tmp/config.yml
    register: res
    changed_when: res.rc != 0