apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: it-tools
  annotations:
    gethomepage.dev/href: "https://${HOSTNAME:=it-tools.hephaestus.markmk.com}"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "IT - Tools"
    gethomepage.dev/description: "Collection of handy online tools for developers"
    gethomepage.dev/app: it-tools
    gethomepage.dev/group: "Tools"
    gethomepage.dev/icon: "https://cdn.jsdelivr.net/gh/selfhst/icons/svg/it-tools.svg"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`${HOSTNAME:=it-tools.hephaestus.markmk.com}`) 
      kind: Rule
      services:
        - name: it-tools
          port: 80
          namespace: it-tools
      middlewares:
        - name: tinyauth
          namespace: tinyauth