---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}-bootstrap-claim"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${CAPACITY:=1Gi}
  storageClassName: local-hostpath
