---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}"
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: "${APP}-bootstrap"
  resources:
    requests:
      storage: ${CAPACITY:=1Gi}
  storageClassName: local-hostpath
