apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app readarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      readarr:
        containers:
          app:
            image:
              repository:  ghcr.io/faustvii/readarr
              tag: 0.9.0
            env:
              READARR__AUTH__METHOD: External
              READARR__AUTH__REQUIRED: DisabledForLocalAddresses
              TZ: Europe/Copenhagen

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 8787

    persistence:
      app:
        existingClaim: *app
        globalMounts:
          - path: /config

      rclone:
        type: hostPath
        hostPath: /mnt/decypharr
        globalMounts:
          - path: /mnt/decypharr
            readOnly: true

      symlinks:
        existingClaim: symlinks
        globalMounts:
          - path: /mnt/symlinks/decypharr
            readOnly: true
          - path: /mnt/symlinks/readarr
