---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}"
spec:
  sourcePVC: "${APP}"
  trigger:
    schedule: "0 0 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: "${APP}-volsync"
    volumeSnapshotClassName: csi-local-hostpath
    retain:
      hourly: 6
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1