---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app omni-tools
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app

  interval: 1h
  path: ./apps/base/omni-tools
  postBuild:
    substitute:
      APP: *app
      SUBDOMAIN: *app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: &namespace omni-tools
  timeout: 5m
  wait: false