apiVersion: apps/v1
kind: Deployment
metadata:
  name: huginn
  namespace: huginn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huginn
  template:
    metadata:
      labels:
        app: huginn
        app.kubernetes.io/name: huginn        
    spec:
      containers:
        - name: huginn
          image: ghcr.io/huginn/huginn@sha256:e25974b8b3caf2e487216c2eabea46ef501401a38f69cfa908e4b294ab4a78d1
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          tty: true
          stdin: true
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: huginn-mysql-pvc
