apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huginn-mysql-pvc
  namespace: huginn
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
