apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-ngx-ingressroute
  annotations:
    gethomepage.dev/href: "https://${SUBDOMAIN:=paperless-ngx}.hephaestus.markmk.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Paperless NGX"
    gethomepage.dev/description: "Document management and OCR system"
    gethomepage.dev/app: paperless-ngx
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: "https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/refs/heads/dev/resources/logo/web/svg/square.svg"
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`${SUBDOMAIN:=paperless-ngx}.hephaestus.markmk.com`)
      kind: Rule
      services:
        - name: paperless-ngx-app
          port: 8000
      # middlewares:
      #   - name: tinyauth
      #     namespace: tinyauth