apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless-ngx
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      paperless-ngx:
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.15.3
            env:
              COMPOSE_PROJECT_NAME: paperless-ngx
              PAPERLESS_CONSUMPTION_DIR: /paperless/consume
              PAPERLESS_DATA_DIR: /paperless/data
              PAPERLESS_MEDIA_ROOT: /paperless/media
              PAPERLESS_OCR_LANGUAGE: dan+eng
              PAPERLESS_OCR_LANGUAGE: dan
              PAPERLESS_REDIS: redis://localhost:6379
              PAPERLESS_TIME_ZONE: Europe/Copenhagen
              PAPERLESS_URL: https://${SUBDOMAIN:=paperless-ngx}.hephaestus.markmk.com
          redis:
            image:
              repository: docker.io/library/redis
              tag: 7.4.3

    service:
      app:
        controller: paperless-ngx
        ports:
          http:
            port: &port 8000
      redis:
        controller: paperless-ngx
        ports:
          redis:
            enabled: true
            port: &redisport 6379


    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        
    persistence:
      data:
        existingClaim: *app
        globalMounts:
        - path: /paperless
