apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mealie
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag:  v3.0.2
            env:
              - name: TZ
                value: Europe/Copenhagen
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
              - name: BASE_URL
                value: "https://${SUBDOMAIN:=placeholder}.hephaestus.markmk.com"
              - name: ALLOW_SIGNUP
                value: "false"
              - name: DB_TYPE
                value: sqlite
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 9000
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/data
