apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-auto-languages
  namespace: plex-auto-languages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex-auto-languages
  template:
    metadata:
      labels:
        app: plex-auto-languages
    spec:
      containers:
        - name: plex-auto-languages
          image: remirigal/plex-auto-languages@sha256:54bd9cf5d399514b8ed3052ce1d01a14375825a429653cb06da129685740889e
          envFrom:
          - secretRef:
              name: plex-auto-languages-secret              
          - configMapRef:
              name: plex-auto-languages-configmap