apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: riven
resources:
  - riven-frontend-configmap.yaml  
  - riven-frontend-secret.yaml  
  - riven-postgres-configmap.yaml  
  - riven-postgres-secret.yaml  
  - ../../base/riven
  - riven-frontend-ingressroute.yaml