apiVersion: v1
kind: Secret
metadata:
    name: riven-postgres-secret
    namespace: riven
data:
    POSTGRES_USER: ENC[AES256_GCM,data:UTZNQrZTf2HZ2H0w,iv:uS0yQ9Pa+gnnPqkhEa2agLvZ3iGi0RJ+dycC0C8XryU=,tag:13Lfs2w7Evcu89N9xLhkWA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:GlKnrbzCUb+5+9iv,iv:erboscKvIHtficW3ygBLd0NQMBesuVL1o7pvwI6yO/Q=,tag:Dgs5pRo5OdERdEdTeQnL7w==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:SOc5M88Ui1M=,iv:TQQEE5jv0deKw7iAriZRkIjDahYyF4CIJkiyZT5Srpg=,tag:kvUA1o8WzuhacKKVRj9MHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-27T18:47:07Z"
    mac: ENC[AES256_GCM,data:6wA3LmKJaF6bL7G8JNPDfw+Eb5s8Nhng5TbIBUnX0fCgdeTy5pF7DmB0xr3mkz7DloYA7SHyms38VYpa+w6QjdvWBxGC+qUu7yGJRbyNJu3l039+dAn3zzPNcVQqDG2+tf5J7lIoU8cWlvB6NdbcBwZgjj7p47RgSvq1P1IscEY=,iv:UB9ht1yJKY1kq2NtWg97618eACa9eQcS0GASuaFTlJA=,tag:lDu4XkMYkas8hzIKFkpOUA==,type:str]
    pgp:
        - created_at: "2025-01-27T18:47:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1QMO9C2fUgHAQ//ffX9kQoiJDng6z4I0Zae3dTwWZX4R/HyGEpUAp7M3jPK
            WTkUzcrwB6LhJRwWTwIixhqsCyxmijJXyOENt3kqAEboWRKcJQGKp5wCqoJGr0Tb
            8YQrfSo5kYsAxB3hGruT5faq2G7j9Ogm65KGeUF00+aKuxc7Q/wWHhODRxBzyWi7
            pV3xkd993ggde1RV0af8HkcHS0s8xBxm864yMNWt6liKnsAcB18YwmGd2I8+Livm
            pm/g/L1bGVZKugG72rLgvqHCYXc1N1leTyVsQpIARUmgY9ylrsx8kRXVLpFATGl4
            JaAserEm+33o/cpIgrgj1YXQNk9VKfrtBDWWfJzGRGYb8ybQ0IesLPNTR1by3WdG
            yPv5s7bdwHTUJtSb9em8HTnLuGPctIcAt9NgTqozQ6kHjyvznBYv+MoHlmmD0u3R
            F+EQSlR5cU2iEp6/dbPllpEDUGd4mq4+YgLQpkct5W6ydmqYJYfrs61mypA3b9M6
            NnuUmA41+8h1vKFKElLVaT96g8Qw7t9tlrgaVAs/FGLpb76NbgbcTHb6JWmobeuB
            T4wID5oikjOf+hOmvuKfofjsb4xSmgliuXNK4ylzaUPUMaOYTGAOU+92hTEv81fk
            CpLXLQfKzpPbYZ7WYPy48zyF1icfcNZZwO12NgVP7F51IUBeRYnXHIXVUonRhazS
            XgGR4fN6Xqnsrw3Or5lMwdEVRIL6Mshv2lppZTmFxl2L4+xZKko8sPSLnhXys+kQ
            3wCDI+Lq2mRrTkn4CE7cBd1WOIJdOxCHNn19PUTk6Nlh6VZ5NLG9bEBle0NoBIU=
            =h26+
            -----END PGP MESSAGE-----
          fp: 62B3C5B8EC6990998E0F1066A6BE93F34854FD9F
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
