apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: democratic-csi-system
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: democratic-csi
    namespace: democratic-csi-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    csiDriver:
      name: democratic-csi-hostpath.cluster.local
      storageCapacity: true
      attachRequired: false
      fsGroupPolicy: File
    storageClasses:
      - name: democratic-csi-hostpath
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: false
    volumeSnapshotClasses:
      - name: csi-democratic-csi-hostpath
        deletionPolicy: Delete
        parameters:
          cluster: k8s
    controller:
      enabled: true
      strategy: node
      externalProvisioner:
        enabled: true
        extraArgs:
          - --leader-election=false
          - --node-deployment=true
          - --node-deployment-immediate-binding=false
          - --feature-gates=Topology=true
          - --strict-topology=true
          - --enable-capacity=true
          - --capacity-ownerref-level=1    
      externalResizer:
        enabled: false
      externalAttacher:
        enabled: false
      externalSnapshotter:
        enabled: true
        extraArgs:
          - --leader-election=false
          - --node-deployment=true
    node:
      driver:
        extraVolumeMounts:
          - name: local-hostpath
            mountPath: &path /var/mnt/extra/democratic-csi/local
            mountPropagation: Bidirectional
      extraVolumes:
        - name: local-hostpath
          hostPath:
            path: *path
            type: DirectoryOrCreate
    driver:
      config:
        driver: local-hostpath
        local-hostpath:
          shareBasePath: *path
          controllerBasePath: *path
          dirPermissionsMode: "0770"
          dirPermissionsUser: 0
          dirPermissionsGroup: 0
  targetNamespace: democratic-csi-system