apiVersion: v1
kind: ServiceAccount
metadata:
  name: n8n-sa
  namespace: n8n
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: n8n-read-and-delete-pods
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: n8n-sa-read-all-pods-binding
subjects:
- kind: ServiceAccount
  name: n8n-sa
  namespace: n8n 
roleRef:
  kind: ClusterRole
  name: n8n-read-and-delete-pods
  apiGroup: rbac.authorization.k8s.io