apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  releaseName: n8n
  interval: 50m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      n8n:
        containers:
          n8n:
            image:
              repository: ghcr.io/n8n-io/n8n
              tag: 1.102.1
            env:
              DB_SQLITE_VACUUM_ON_STARTUP: true
              EXECUTIONS_DATA_PRUNE: true
              EXECUTIONS_DATA_MAX_AGE: 7
              EXECUTIONS_DATA_PRUNE_MAX_COUNT: 50000
              GENERIC_TIMEZONE: "Europe/Copenhagen"
              N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: false
              N8N_PROTOCOL: "https"
              N8N_PORT: 5678
              N8N_HOST: n8n.hephaestus.markmk.com
              N8N_LOG_LEVEL: info
              N8N_LOG_OUTPUT: console

    service:
      n8n:
        controller: n8n
        type: ClusterIP
        ports:
          http:
            port: 5678

    persistence:
      config:
        existingClaim: n8n
        globalMounts:
          - path: /home/node/.n8n
