apiVersion: v1
kind: Secret
metadata:
    name: decypharr-secret
stringData:
    config.json: ENC[AES256_GCM,data:yubxnhVzh9RO1b8hZl1AfanFvepem6lcTttjG+aHZGK2By59USLt5dTHzkqfrGi8TJGoaoLfYie4xrThdHxUT27GujBuvkzDuQ3qhhODBwV4vH2KYnjhPTl5q50KMqP+vLCqCkuPRfeJo7NzD28w4XIdx26DRyg+O6r2mzhLCoz2M0uvGQA1zqfxbX+A/T3v36Fabn8inse0Yibr+YD+VS30+Dccb1kth7WllH3SOhQBMri8wi32QVbHDOq9Z8yBfcya/P0vbttu09INOllnnyq8TJCL0CG4hEWZmSCMPURQxnW6yQSkCPfuDKVXPTBgVEpwiEV4vqQjDM2538m/xNxZfXOfHllRjO6NS0nH3govj/fKA0r4i5EP1xxnmF7ZCELPAHywBx68MIWg6vHGtNTi+AsLZIlrRrZE6BcR0g1BRZbWTdX6zvGUDjj6Q58MAr7YpYozKLHAz7JFBdg5BmvUG2nZ2thQkF7Y8yZuKvS1smfHqKQSKZJUjpz0dSbrIji9SO+LJadCpAT/yEdM+dUsBMgG+PQqiM8Aoa8CglZuytbaFgeAu6qZIS+ohdgq1gAzTrK/vNHr5Pe2ClPyVDGFBgaI9s6fiER88DzyXWKK+QbftbKZRmqZAkBsH3v7adMiat84Ct+Oi47v2WH6LOFg8pgnr2O7q2RG60ZScKhD6UUl7348suOu8TIOR5XdLCpPvFlArCsRr8MYLrQgjmzFPsUevF/nEf97CgtG0nMucJ/94lHI/NqGwb1Blv4TscMoN+UWO0/EhVcWREMCQugTQosiI9Xt4wogwhGWnfkMUKd/u9NyGGo068ZmX+Y1AgKfT6ifnUOG1YDS1fGe5y3XKCGLxk45u9rl+MXg8GcuPTt11FdkE+2y8PkMJGFOsDJ+/PQAP278laHZO+/SyUWrz9Hrn7XPVS1o7EhuSPlaqGy4qX6Q4qqveWDlYpvN70WyLL4oZixN1ifLJmFI9PRqGI67p/qabXcgb104ngxx8rWjFGm3BXsm4ZD0T83LuLbhXOI7P8S0tctSbTMPWD+pWalDqy8K8gx9cuUip90pIM7Nth89gPHLNel+ZV7JGbayq3wQi0jUiA0PGD5N05xPgZPuKw0ax3+kMfevTM5V5/B8FLmvOTid+yvzCNb5eMzxZBTar51KdPUN3Cz18rnhra/MdVByaM+FhEA/pQsQpMuz0kQAGWi259AS5pcLyQcmWXBa99syhQzpKjpXJ4lDzJ4gl6gO+sxsILnQe5fY2bznfoEkSAyyHLxK0qe5v/qUWhHuptUgGcWS8G6v48FR8n+FRllMuC2Fwi3FbCIOP1dn4YixbGpGfHY83cMpsUHuQI6G0G9U0DM5F0FVyHeOkcU5TmN/FJh+SV6aY2ZR1ylAUkDXIF3/BEH3ewKLS89jTZSzAR7bP/9MNFKY2qrbWQZcLrR04zozl72coP9Pd11MXtEHggidkNp6iXiSnfeLZbuVcLNr+OEpQVueE/O5UNahPbvLu/K8jh+awRkCq7QTEOC5B2sinCTTw1gNcKzfHuN97tCTZET0UnrlokITG5N7ikOU7T14FCzvS9yfoshCwm3OZD/fFqF1HYdAevDpZFlXZk5xMCVxaghPv7b3f8AjEuA/FO8AqVANXM0ge615V5pVP/iqSMGdi6Z3nXUDerTVSk61e3tt+dLnH1IbLgzBiw==,iv:r4YtApjbpcVofYnhb/OR6nCbpAL1L0RE1PhyXmUa7yQ=,tag:3filIjDOwKtNEsWc7KJzVg==,type:str]
sops:
    lastmodified: "2025-07-06T11:18:13Z"
    mac: ENC[AES256_GCM,data:qayW6jqZOLwidV8lYQv7W8ODa/yvaN+k6sXfzzOk12a5jU+CrIRGb0bq4R2NQUKqewlzQEgbe04k6UABY5NaY/0Ncl1sGoCMGwNtmCF78nNlv9QX3esZvZHG7U4J1FJNFUigqZX4vKyGuRO0GB8hMuq5qcLeaZWYDTZ+lbK0H9E=,iv:MyG3vP14JEs64t1o1LDaM8eqNzIXGvfgKHl+rZxWLd0=,tag:mKRbBJygtQgsFB7q4lTQ+Q==,type:str]
    pgp:
        - created_at: "2025-07-06T11:18:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ifymI7TXLxARAAlZtM81gaq1qnAvg9cqkf3qiGPvEUV2K3XJRQS7Z+iurL
            usOwnqW5ByVlQ7dqjfLg7c6FB5jdtcUJ1nO0DgrR3AYOjoc62XhGHXaXtkbS1FTC
            CnBHKjkji2ZqKVZ1KV+aj7Dh7VZ10J4SEeimvnXIlTWst0SkErGDjDFz1FpVbHl9
            xDUdEUMxerXj7WlQ+a+jknL9RB+YcILSScOhckxX5XkFsIy1l7A9QsamQm6j6hQS
            lqdHdUPEqwmfG45nOsKeWuPG4avjncE6JNAp0MuFOCC3LWBz0UEJt01X4w2hPkd1
            bTmbtPfye9XVxLewb5px4HfpkHSk/fm2PuLZJgn+7ppTXIBOqUyEOeXNNAfEXMkR
            lzzFRtS1eQOyVwG0UwPACDDX0P+2A/AouswCe8pFU0LCAJop61WvCILmTnuydex6
            bwOhqi1UUo/i99PVdnW7HoJdgAlAp8dAG77EZQ2xAfjkgJ1BuNijFwVkPOAQ03HJ
            Zo3X8n/fF13yNEORyAim39ASu2UUyG/Mbht2myOiO0+ZUpd2L1agTha8uH3UGkk1
            HGAq1SYyL4VqrQqCmlXon/f/dQIV7EzvyssmxrPOYKi7Lu3lmuoVlo+yeKMrYvJ8
            LCkO3r2UBetZ+3QInjETH+yG8UMO6ua9HURucz+bVjhz48rEmGOp3lY843KQvEjS
            XgFUAQzbw1/xbqy/3m6XuLG0qvNFvGDM/4zEo08U9HndfQCRbwXwBv3Flxqjc5ul
            DzZ6T7+nOvHxJpKXtGYA8yr76XPFRgtP9CLwf9K5gRGZXXfX15KwLXkDDJcq2ko=
            =KH4z
            -----END PGP MESSAGE-----
          fp: E6862079C6D05BFFF38F920C4EB7CEF00A5BE02D
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
