apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app decypharr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      decypharr:
        initContainers:
          init-config:
            image:
              repository: busybox
              tag: latest
            command:
              - sh
              - -c
              - cp /tmp/config/config.json /app/config.json && chmod 644 /app/config.json && chown -R 1000:1000 /app
        containers:
          app:
            image:
              repository: cy01/blackhole
              tag: v1.0.4

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 8282

    persistence:
      app:
        existingClaim: *app
        globalMounts:
          - path: /app

      config:
        enabled: true
        type: secret
        name: decypharr-secret
        globalMounts:
          - path: /tmp/config

      rclone:
        type: hostPath
        hostPath: /mnt/data/
        globalMounts:
          - path: /mnt/data
            readOnly: true

      symlinks:
        existingClaim: symlinks
        globalMounts:
          - path: /mnt/symlinks

      logs:
        type: emptyDir
        globalMounts:
          - path: /app/logs


