apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-data
  namespace: tandoor
spec:
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: tandoor-bootstrap
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-hostpath