apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tandoor
  namespace: tandoor
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/tandoorrecipes/recipes
              tag: 1.5.33
            env:
              TZ: "Europe/Copenhagen"
              DEBUG: 1
              ENABLE_SIGNUP: 0
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 8080
    persistence:
      files:
        existingClaim: tandoor-data
        advancedMounts:
          tandoor:
            app:
              - path: /opt/recipes/mediafiles
                subPath: mediafiles
              - path: /opt/recipes/staticfiles
                subPath: staticfiles
      temp:
        type: emptyDir
        advancedMounts:
          tandoor:
            app:
              - path: /tmp
                subPath: app-tmp
              - path: /opt/recipes/cookbook/static/django_js_reverse
