apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app tandoor
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/tandoorrecipes/recipes
              tag: 1.5.33
            env:
              - name: TZ
                value: Europe/Copenhagen
              - name: DEBUG
                value: "1"
              - name: ENABLE_SIGNUP
                value: "0"
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: &port 8080
    persistence:
      files:
        existingClaim: *app
        advancedMounts:
          main:
            main:
              - path: /opt/recipes
                subPath: recipes
              - path: /opt/recipes/mediafiles
                subPath: mediafiles
              - path: /opt/recipes/staticfiles
                subPath: staticfiles
      temp:
        type: emptyDir
        advancedMounts:
          main:
            main:
              - path: /tmp
                subPath: app-tmp
              - path: /opt/recipes/cookbook/static/django_js_reverse
