apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tandoor
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        initContainers:
          copy-files:
            image:
              repository: ghcr.io/tandoorrecipes/recipes
              tag: 1.5.33
            command:
              - sh
              - -c
              - |
                cp /opt/recipes/boot.sh /tmp/app-tmp/boot.sh
                cp /opt/recipes/db.sqlite3 /tmp/app-tmp/db.sqlite3
        containers:
          main:
            image:
              repository: ghcr.io/tandoorrecipes/recipes
              tag: 1.5.33
            env:
              - name: TZ
                value: Europe/Copenhagen
              - name: DEBUG
                value: "1"
              - name: ENABLE_SIGNUP
                value: "0"
            command:
              - sh
              - -c
              - |
                cp /tmp/app-tmp/boot.sh /opt/recipes/boot.sh 
                cp  /tmp/app-tmp/db.sqlite3 /opt/recipes/db.sqlite3
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: &port 8080
    persistence:
      files:
        existingClaim: *app
        advancedMounts:
          main:
            main:
              - path: /opt/recipes/db.sqlite3 
                subPath: db.sqlite3
              - path: /opt/recipes/mediafiles
                subPath: mediafiles
              - path: /opt/recipes/staticfiles
                subPath: staticfiles
      temp:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: app-tmp
          - path: /opt/recipes/cookbook/static/django_js_reverse