---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app riven
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../components/volsync
    - ../../../components/volsync/remote
    - ../../../components/gatus/internal
  interval: 1h
  path: ./apps/base/riven
  postBuild:
    substitute:
      APP: *app
      SUBDOMAIN: *app
      CAPACITY: 2Gi
      GATUS_PORT: "8080"
      GATUS_APP: "riven-backend"
      APP_NAMESPACE: media
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: &namespace media
  timeout: 5m
  wait: false