apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiobookshelf-test  
resources:
  - audiobookshelf2-namespace.yaml
  - audiobookshelf2-release.yaml
  - audiobookshelf2-ingressroute.yaml