apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mosquitto-namespace.yaml
  - mosquitto-secret.yaml
  - mosquitto-release.yaml
  - mosquitto-ingressroute.yaml
configMapGenerator:
  - name: mosquitto-configmap
    files:
      - mosquitto.conf=./mosquitto.conf
configurations:
  - ./kustomizeconfig.yaml