apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-system
resources:
- repository.yaml
- release.yaml
- traefik-namespace.yaml
configMapGenerator:
- name: traefik-values
  files:
  - values.yaml=traefik-values.yaml
configurations:
  - kustomizeconfig.yaml
