---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-proxy
  namespace: traefik-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik-proxy
        namespace: traefik-system
      version: ">=33.2.1"
  valuesFrom:
  - kind: ConfigMap
    name: traefik-values
    valuesKey: values.yaml
    optional: true   
  interval: 1h
  releaseName: traefik-proxy
  targetNamespace: traefik-system