ingressRoute:
  dashboard:
    enabled: true   

providers:
  kubernetesCRD:
    allowCrossNamespace: true

persistence:
  enabled: true
  path: /certs
  size: 128Mi

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true  

env:
  - name: DUCKDNS_TOKEN
    valueFrom:
      secretKeyRef:
        name: duckdns-token
        key: token

additionalArguments:
  - "--log.level=DEBUG"
  - --entrypoints.websecure.http.tls.certresolver=duckdns
  - --entrypoints.websecure.http.tls.domains[0].main=hephlab.duckdns.org
  - --entrypoints.websecure.http.tls.domains[0].sans=*.hephlab.duckdns.org
  - --certificatesresolvers.duckdns.acme.dnschallenge.provider=duckdns
  - --certificatesresolvers.duckdns.acme.email=markkristensen@outlook.com
  - --certificatesresolvers.duckdns.acme.dnschallenge.resolvers=1.1.1.1
  - --certificatesresolvers.duckdns.acme.storage=/certs/acme.json
  - --certificatesresolvers.duckdns.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
  - "--certificatesResolvers.duckdns.acme.dnsChallenge.disablePropagationCheck=true"
  - --certificatesResolvers.duckdns.acme.dnsChallenge.disablePropagationCheck=true
