ingressRoute:
  dashboard:
    enabled: true   

providers:
  kubernetesCRD:
    allowCrossNamespace: true

persistence:
  enabled: true
  path: /certs
  size: 128Mi

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true  

env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api
        key: cloudflare-dns-api-key

additionalArguments:
  - "--log.level=DEBUG"
  - --entrypoints.websecure.http.tls.certresolver=cloudflare
  - --entrypoints.websecure.http.tls.domains[0].main=hephaestus.markmk.com
  - --entrypoints.websecure.http.tls.domains[0].sans=*.hephaestus.markmk.com
  - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
  - --certificatesresolvers.cloudflare.acme.email=markkristensen@outlook.com
  - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
  - --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json
  - --certificatesresolvers.cloudflare.acme.caServer=https://acme-v02.api.letsencrypt.org/directory #changed
