ingressRoute:
  dashboard:
    enabled: true   

providers:
  kubernetesCRD:
    allowCrossNamespace: true

persistence:
  enabled: true
  path: /certs
  size: 128Mi

env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api
        key: cloudflare-dns-api-key

logs:
  general:
    level: DEBUG

ports:
  websecure:
    port: 443
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: markmk.com
            sans:
              - "*.markmk.com"
          - main: alpha.markmk.com
            sans:
              - "*.alpha.markmk.com"

certificatesResolvers:
  cloudflare:
    acme:
      email: markkristensen@outlook.com
      storage: /certs/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1


podSecurityContext:
  fsGroup: 65532
  fsGroupChangePolicy: "OnRootMismatch"