apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rclone-mount
  namespace: rclone
  labels:
    app: rclone-mount
spec:
  selector:
    matchLabels:
      app: rclone-mount
  template:
    metadata:
      labels:
        app: rclone-mount
    spec:
      # This is the main container for the Zurg mount
      containers:
      - name: rclone-zurg
        image: rclone/rclone@sha256:3103526c506266a9ecdf064efe99bf3677d92ef6407af124d8c56b4f49cbaa51
        command: ["rclone", "mount", "zurg:", "/mnt/zurg"]
        args:
        - "--umask=000"
        - "--dir-cache-time=30s"
        - "--allow-other"
        - "--allow-non-empty"
        - "-v"
        - "--vfs-cache-mode=full"
        - "--vfs-cache-max-size=2G"
        - "--read-only"
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
        volumeMounts:
        - name: data
          mountPath: /var/lib/rclone
        - name: rclone-config
          mountPath: /root/.rclone.conf
          subPath: rclone.conf
        - name: zurg-mount
          mountPath: /mnt/zurg
          mountPropagation: Bidirectional
      - name: rclone-decypharr
        image: rclone/rclone@sha256:3103526c506266a9ecdf064efe99bf3677d92ef6407af124d8c56b4f49cbaa51
        command: ["rclone", "mount", "decypharr:", "/mnt/decypharr"]
        args:
        - "--umask=000"
        - "--allow-other"
        - "--allow-non-empty"
        - "--read-only"
        - "-v"
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
        volumeMounts:
        - name: data
          mountPath: /var/lib/rclone
        - name: rclone-config
          mountPath: /root/.rclone.conf
          subPath: rclone.conf
        - name: decypharr-mount
          mountPath: /mnt/decypharr
          mountPropagation: Bidirectional
      volumes:
      - name: data
        hostPath:
          path: /var/lib/rclone/
      - name: rclone-config
        configMap:
          name: rclone-config
      - name: zurg-mount
        hostPath:
          path: /mnt/zurg
      - name: decypharr-mount
        hostPath:
          path: /mnt/decypharr
      restartPolicy: Always
