apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
        app.kubernetes.io/name: audiobookshelf     
    spec:
      containers:
        - name: audiobookshelf          
          image: ghcr.io/advplyr/audiobookshelf@sha256:106531342a5f150e0e3dcbb348f126a5c452ecc4274f162d31545194dbe4352a
          ports:
            - containerPort: 80
              name: http
          env:
          - name: AUDIOBOOKSHELF_UID
            value: "1000"
          - name: AUDIOBOOKSHELF_GID
            value: "1000"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: rclone-data
              mountPath: /audiobooks
              readOnly: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: audiobookshelf-config-pvc
        - name: rclone-data
          hostPath:
            path: /mnt/zurg/audiobooks
