apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app audiobookshelf
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      audiobookshelf:
        containers:
          app:
            image:
              repository: ghcr.io/advplyr/audiobookshelf
              tag: 2.25.1
            env:
              - name: TZ
                value: Europe/Copenhagen
              - name: AUDIOBOOKSHELF_UID
                value: "1000"
              - name: AUDIOBOOKSHELF_GID
                value: "1000"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

    service:
      app:
        controller: audiobookshelf
        ports:
          http:
            port: &port 80

    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /config

      rclone:
        type: hostPath
        hostPath: /mnt/zurg/audiobooks
        globalMounts:
          - path: /audiobooks
            readOnly: true