apiVersion: v1
kind: Secret
metadata:
    name: tinyauth
    namespace: tinyauth
stringData:
    TINYAUTH_OAUTH_WHITELIST: ENC[AES256_GCM,data:5iuHh0zFDtzVD/MQJmT7g12DSHY563Sv/jTdl2fcDJSg8b20XJHu4EHU+u63kcwHPUt97ZFLMUoZP+NxkrK/f84DqW5tOwpazbY0G1xPYQ==,iv:uT9lzz70FQSMq35bzgpeavdICrCnQe86xkHd9GHCRQI=,tag:skzhRDURiJVVC34tR5AIQQ==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:W6PliD/73+xV7T6j87LtCkg4m3k75EoPs2iG54SOOwmnJwkPQVpmfLnaCYCaLtNJctTqALe37+OyFKDcXt90inp2lgOyVWKc,iv:K2HN0P64EvmuM5/XGF60MkICSMa1HF8Wm9BanlNrhVw=,tag:v7gJa39iE5+Ng+wKYRTuDg==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:FzuKexAMlTeZOTVBlH2Td6cEbz3GEXrwXWN2EZiSIDZ+GZA=,iv:PrQVbLMHIurGWxgcgSYdb7KLHwkC5wFpcUeWXiPqkWc=,tag:yFK1gVhpMRupKj6N1WP80A==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENT_ID: ENC[AES256_GCM,data:ZFq5VNZi1OW9pMjZAnP6K8baOjgDWfyVKsdKzlVj9Cw1RCSt,iv:Bnolkljv66zqncM2HGmDGSuRxdunF2wB6mEVSkzVciM=,tag:vN9UZ+oJGbwYnrvMOOcdLA==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENT_SECRET: ENC[AES256_GCM,data:DHVEPOU0WtZraMPS+dZl5V4zxgzTm8pwYFJ7rCnRM0U=,iv:+nZ5bbBXW+zOxQWF5BMi8neo39LkgmU9xp+9Gbt4tKA=,tag:pKgseKUi5XOwhKjN/QOu4Q==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_NAME: ENC[AES256_GCM,data:TWSjpLMKpYq4,iv:LBFnqf2WA1uTD/aaQm7fEHPBFLwIHxFOJ6GjU13d0k4=,tag:WksWyT4icW2h3Djv8KNWzA==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES: ENC[AES256_GCM,data:hAE2QoHu21uzGpEiy3RtIRxi4Fn5HPrmtRIu,iv:rjwnJ+YW6vBGXv3Zb2wtOPEeW87JavDMT8Al/+EKGb0=,tag:uVl12QRcShbqvcvKlYXXtw==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTH_URL: ENC[AES256_GCM,data:QLp+zGp/sSh5ubeZMPSYphuxXCQloIeGlbmPzlmjbCp3MW7+ZCoTAayUdDYNbU/NGQ==,iv:Icp46SZXBZN1eJxq4B8QajdPj1L3+dE838yL/zmK6pA=,tag:zdfGQE5a92GEBTeUZtpORw==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKEN_URL: ENC[AES256_GCM,data:IG4STF4cpcRyoHXSKwQ1uGzif8xr+GuBXlJ0v20pY/SzXyrzs7ROX89pPDDz2wGF9ajnwCln,iv:k/ouuMuAkFvQkLFUEsOZYwcINLaJiwytQxxW2CdfwkA=,tag:NVnARaIjiM8QQkyYTlGerw==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_USER_INFO_URL: ENC[AES256_GCM,data:EBuUkrK28up8fc4CCDhstApWJLpxJOpAtFiF896Un8Ss8WIrxBalqa5L8i6QufOrwgiJO86skiy8,iv:cyW9wSkP2KVxKY9y2lMxnZ0RNlqXyrScI3nlkmAcI7A=,tag:kq8EB/HpbXc0F5XzlJuklQ==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_REDIRECT_URL: ENC[AES256_GCM,data:OjMtOW4Pu5SWXlyBXBxGZGfbJS8sw1mSmZ4S0sxjigci4vXxcmECiX2GTjsd6OLcR68ZP+6GJt1qWVBJRnSjjN07,iv:DMT+oA8qFxkwD1EBmMrQ61s+csG9SUhpASN52XrN+ek=,tag:Mr8J2KLRehF+WCGaMmWpEg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T19:47:10Z"
    mac: ENC[AES256_GCM,data:jTzv+4WUMZnhz0SbIIpKPcgAhLoXuBIj90qJD4iqWBlZeIUX00Wm1NUI36cK/6vX909jjDwAubPg3ykQpwg3f+84UR/Vd7MmX9OWCGw5CUU3tbdS+28PdkFANuP7K9bk7LlReK0Kdo6TLmQS8+rgRulNmkV+kPDGb+nZ2iWuigE=,iv:smuLoCAAJnQzMk6cFQaMUoJ/FVmetEROMiFEH00HxqM=,tag:IyY2lz3j0vpQ250HBxKy/Q==,type:str]
    pgp:
        - created_at: "2026-07-18T19:47:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ifymI7TXLxARAAhxrTJqbQtOqqPK6SkcC9zHmrrrdFILKcZavsVEYLcsay
            B61bql3tu/CGJHi47Ww2CT1APSIJ/ArHWRsd596LKtjxqEFxsdKRKenCU9m6tJ2M
            +f9AlyhBwXk5n3gKDlz+ysR54/iNwhJZnvCvrs3MROK5YLDuHoZAQu4Yo51jbX0o
            kd2pRhXUd+YIcKQNIber8rMvzVbS934/dGK/583sec+eInusPiFyGlacIWrJeGhW
            AjW+iy4kSyr21YQf8QWocobOPbuzbrHyotrd2u1o0YDZyi/J2ccpxA37aswh86QS
            B2svX4mGqWmo9ikQHnP7EI36IGjnX9HpWo3l3dLxqkkbY/VWCfTh1UgC9ldpdJK4
            sYJWPZ3o/XElQlAiEc6v8zTPwEDNfpubTYeBLYOHZrNW9QFFbcejN2wXQ5uIBWeo
            hLzmmDd1xNubxQF5DEd4HZmrOCR+rji22F+s1UrwQEUL2gbbfSxzcsQ0pT3JXi2c
            9CijBKzWDMM6pySBoYpVmBCyZfHnqMzZoRK6yIUgJzE08Fizv0GfGZLDKxW5rIMg
            Sl6fcsFukIXmDsBEuAJqVElsdc7/JdYw4sp/cubEdu78JUPYMwwRJFUWoOawjIaK
            A6iBQQua7LmAtaY6dSkj+jWNiSELzSeAZYPFZs71IF88UiM248NQbNJWHeB3fO/S
            XgG5rA9ic7sS2ObJ5h6AKy1ZHTKKsp4Z2aLfE9HrGQ0c9qJckfJaklnEz6b01KYR
            WZka4hu6RWm+3oy2fRFh0v33Jb9rxE+K2+xI8OsvI9U2JFZVNbBjeVEb6DhaOUA=
            =CUaQ
            -----END PGP MESSAGE-----
          fp: E6862079C6D05BFFF38F920C4EB7CEF00A5BE02D
    version: 3.13.2
