apiVersion: v1
kind: Secret
metadata:
    name: tinyauth
    namespace: tinyauth
stringData:
    SECRET: ENC[AES256_GCM,data:B0oC7UCExC1PRfKw8I01/24giQGZHqMnRFSrTwDBxhU=,iv:cxSRKldFh0/JjIEm7o+oIe/C/oQmzAzIybyQUVvOMJI=,tag:IIQHGkCL+kGjW8bN8zunyQ==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:eQ38/YUu1nLJdvrvxR0cgvNI81hJ/syhVS0zmQqQgvN1fwBf+Fy96YcWi7RWH7eAzng4QdvPJUzDc55kXr9pvsYwVHWo0r+G,iv:GxTjxNpg/I08FPPs2d+251OBj8oFw8tKGeoLJX315SY=,tag:eGl2+ODlVf7NDmWnl1HkQg==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:98Vy+2rSeC+SRTbwIj+WIVZ/9d0uf/wexmxUZdAJTKpE9XU=,iv:KXrUr8tIGWpVIkiUJw6vKULjJu9tbgEibG7FlmYooZY=,tag:E6VkT81dk8hMNg8PwoYM/w==,type:str]
    OAUTH_WHITELIST: ENC[AES256_GCM,data:jQhi6Zk44PDOY9+CMmNdtbF6C4oIPdjWkQ1gJZZF7PTE+lCcD/E5A1lQoOiBM7cYUD5G3w==,iv:EpPFDKeKPwT5cXDmjawuqv5t9z12/ASzFRrC6JOabgM=,tag:2JqCJh+olRN8VAX02HKomg==,type:str]
sops:
    lastmodified: "2025-05-04T15:23:43Z"
    mac: ENC[AES256_GCM,data:zpbh9PD8BFm7QQ42zK6LNmIcE8VIIK79iqV6R9g0OK7ohVfjLUnxHaD+ei6zlCDDoALmLL5sYODSKH49aG8WEte0sxcWT4g/6n1b0Q/3ap27cjHqV4zZYjd9qASuvh/U0XN/yF0DmjFdGwvudPyLFPyVLu4JEDMD9o1R5EmWmHY=,iv:X6SpbsxVFRUASR/V9OaQThHaaaGPTZaiQ29cgECiy80=,tag:WBVOR6YvQyF0cZRWUtLdBg==,type:str]
    pgp:
        - created_at: "2025-05-04T15:23:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ifymI7TXLxARAArSaXPk90Dfi+hVYCHaux19DG966bsg+rXR0ljLY5P2e5
            UP4vo/NxTpajYFW2JBQMbQOrN9WVu0cawlDqwrO9jsmXdc20+G69omf0QYL9UdCA
            mbTYoIiCKJR23d48kcph+SER4TjLKBBLDQsKglynH/LjQCcvM7YxR92PCpWSSDDN
            V3xZjwHAfWOBKeiEPvoHanq5QePu6cm5decSITRdxXv9yHXVoPbq+yjpihPCYNJf
            RmOX6wkJuAfDyeSs6NsXAB3gdwF+Db562Fsf6DieMFlU30F61Bj794OpzkTdGJT7
            NJt17nm59hDqnDI/OIi6a59uxbSggnC/hLlWfopISUTRdqqcVqrASmHvWEW2azeE
            KnDInu7HQYjMxrTw6O2FMhxnq1BAXRhe2OF8dZ8VFfT+ZVOMvY12B1aNx/V0D3W7
            u6kgxiqIuLfvdmHADLsq5w7s5ukC4E2orqCtlbceGrqxorBJgv0kFda2vAXYTRXi
            ieThSz8+9WyI+qY+vRkFQixjjf45QmOfpyzDaqo2gxhKi04vH//x8By1rLKSB0aY
            Fpg+B0PftwEKfZAeCT8vY8gbNyf5z76vjonGcuQvjj3YXu4iKaWimrzJDmHuRwgu
            sx0Ut7HfWQdGAz9GqkeOXF2HXsWiFHiJOkwRbhYHmFPCXcWOIkvYQ3HQBH/giITS
            XgFLmGUJfRGx2dsC14PR9ukS5+WC2VUHFVPV2836Ggtfk0MI4/zsZshuMz7KE7YH
            m990T/1xxFBFSHqK0xSJ9sl0nEzJm3c79NznLP1CZxzSrlG9IaM/v/CgrEMmHLo=
            =WJlW
            -----END PGP MESSAGE-----
          fp: E6862079C6D05BFFF38F920C4EB7CEF00A5BE02D
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
