apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tinyauth
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      tinyauth:
        labels:
        containers:
          app:
            image:
              repository: ghcr.io/steveiliop56/tinyauth
              tag: v3.2.1
            envFrom:
              - secretRef:
                  name: tinyauth
            env:
              APP_URL: https://tinyauth.hephaestus.markmk.com
    service:
      app:
        controller: tinyauth
        ports:
          http:
            port: &port 3000

