apiVersion: v1
kind: Secret
metadata:
    name: tinyauth
    namespace: tinyauth
stringData:
    TINYAUTH_OAUTH_WHITELIST: ENC[AES256_GCM,data:QDTmFSqa0FY+vRM905c4bpI/lsX0A8sN9WnTg5057zhiAFIeTM4vmCUugjwt38/og58GeX1NBLVsDvDGM7FmLEKSCh98UjBY5b+3/bGBoQ==,iv:y7Fq9nz5E30oGu/WlCwimNtYsB9YiPKZNrVP46sEdJ4=,tag:4z0aP7hAAIlMSYVg4AVWnA==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTID: ENC[AES256_GCM,data:zEr6xgFokttJCjTcwinbBS5TVr547WJlL47vSDkH7RSS3Xf9Lj7QTn90x0QCtk2ZHvMoEfZX7v21Z9HU7+NDTcGxy+wycZ2P,iv:9S6z3e20N0VHmSunDlnLcSAoCbrVm9ei9BsjSmPtjLg=,tag:py8VOMk9jRTH1S+y8+dA9g==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTSECRET: ENC[AES256_GCM,data:psW31NTu7wBqkaKzAcUfK2xmrrHJT8+mJfkITtFszWzF0iY=,iv:iEaR3FsWmYtmQur2DJBSq9rlm+1h9kP79hikBY2J7EU=,tag:kCEpa7latpwfNYTsapMiQA==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID: ENC[AES256_GCM,data:H0qZu4MrNskuN6lJbNjG/1SdFl2KF/FGhbMh2Ignck/6sjHt,iv:jyWeng8okxLcH6eSpdAsLTxKWJD6NRGrC0WxG0pucXQ=,tag:Fxs4EZJMq2C+BZxubplYLQ==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET: ENC[AES256_GCM,data:G8XlJHuPlNXaOSPIfHFBXU3JOU2J8gxvd6c5Iby3hdk=,iv:iuxHdJtKMBAPzHgDyQmCo/fy+/A6l/Eh05negE3JYGw=,tag:JMWfpd8kDlhPFuFPkFCdpA==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_NAME: ENC[AES256_GCM,data:50bfaotAeQty,iv:zutTYUljNf8LlcPAZ5ay4Ww91j7T4C2/0e8/Q5rXYbg=,tag:VXS+WLhz9Tu0B0c+FH9Xew==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES: ENC[AES256_GCM,data:Nf4lsjX6JMZz9H3jDG5I/G7vJYmAZWVO29b9,iv:nlC6kmhjfuPdC6/9fgFukhY8pzKDB6WZAPngrAZrOrI=,tag:insUcPaveqSbG7yyJvQDEg==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL: ENC[AES256_GCM,data:D5f0wTjIdR6Q54u7Jz08vU4igNyswm4jUCUXLRxBhV/7Izdqy+38Y373bf7jAxyjbw==,iv:/iLLZ19iVeLM7zWTIFzXriuBZ9tCf9QjsPA28Foz8qQ=,tag:Uk0zW6yFNv5humKeGXJQRA==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL: ENC[AES256_GCM,data:7HZd+6mICnfTVsP/74KiyEKyq34FG2U8LxF2ekQf6gV21OlAgfTb10qLWuDxKsGIx5ym/tWj,iv:7dzb4tjM1kyyiZVfmZCpSXwuSExOB3V/NgRud1zlqRU=,tag:1GfJc12vWxRJ0TVaA6Gunw==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL: ENC[AES256_GCM,data:L6mFqN84UzKIXX+nvn00L3LIbYKapEdC+l/0fs26UT+hwy+ZzBGG6qucRXGSsd+YHXyF2L10h4Qq,iv:XIXl4z6Sd4h1n2m1oCuLWRyn0auxfz6FOXudIyy4gMc=,tag:VpSLzbuwyY49iZQZVXBkiQ==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_REDIRECTURL: ENC[AES256_GCM,data:lhG3F2wc/iZzThzIsQ8pfTO+ZCW7AV9xosw3iVVun4OPvyIUnoiuKiwmfLNtt1HjOc9u5RC77pbNX9FMS59xmc/F,iv:jFWjPMoaybcgI+mR1d2TZn+uPkiC5bfgyOzbZBQ7Y74=,tag:GdDLImMFX2YkcBdX9u3quQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T19:52:10Z"
    mac: ENC[AES256_GCM,data:PN0gMEosEdTg9zYgxQLRJKz3rMeV4pxwd6CiJnyCE8A6zPpNBEe34oANKtDg675NTAsHOE7Uhtq4AkbL5LTgrZIuld70ZtH9KKMe5w8sZWLlKGQN99775AoGmkmUNCq5NOaTvuWA9WU9wymGmUVhC3FGa24H/x4dxu/PsRWb0EI=,iv:EGF+dqxYEUyjVc3fJtv3L4w90aXwIL0XAGqR0leq8zc=,tag:uQfUXcdroym36Q7NYdyfvg==,type:str]
    pgp:
        - created_at: "2026-07-18T19:52:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ifymI7TXLxAQ//Vo4QVCLtm1TMSMv5y3AjYKYWMlYj85R2Jl+s9Dz4BD63
            lgsyO7J7wZyCKOlwGWQc7S8nv4JxVERMHLWFPjcPgYxKQ1qNGs9zMwCYiH0f3YUX
            haSBnsJsb5OZ9S7z8b+XhxU+OLc3whYMebEAMSwhWYR9ZXB2Xwt73dM0wPyJbZ4g
            c+19lQO/mxG/n17DA55kVul7jjeoGPFanwdEiTehnCZa10sbZiI4qY1v8hPHZWL+
            cPK4/MX4j5LgRzOfHT9SEgLkV37MtAR443iGJXBGht0Vul+5M9d8owXSjOSNF769
            9lclHJ8Gaw3rkeJeBzpLRUB7s2FRT9C1mIZJaokXACR3Dxo4fIxtNf+Q+1J4ntD5
            BKPzXlA8tv/kqPU95RzT5rtLfk8/BQaDxwqsC7o2RZBXmjt/z888tsbnl6ZemTbh
            /t+jUfKYXJaui0EFmLVZHGat/GpOaXn/5LwqWc6Jjr6XzCOc/2y6k706cHht+Ps2
            lOB9JJQy4sDKKuGud7bRXGLdDeIsKgs32h5lxGoej/f45rPL19Nstux+t3/nNxdb
            NBVAJdVqyE31L5bjOPACU6+btZLjYiPDKMEpTopUMiApiqi3SboDtIvul+dQE6L2
            azFbbhgNo+YBqFR78QJVX47xwMj2LX9qy9Nm6ZF/YxnU4C5vvwjLvraJclhWZYnS
            XgFTgehJCHA3ZvOpdkLKB/Kqua4e//Z9CVOB2uTnFSELkfKjjLdFqk740zFpn2Pv
            J+WGt6YoVx0+Fkir15tqsID7k1mUB+S4I/WlakRW5jKoC4nj532AQCP/j6vEjs0=
            =FxpK
            -----END PGP MESSAGE-----
          fp: E6862079C6D05BFFF38F920C4EB7CEF00A5BE02D
    version: 3.13.2
