apiVersion: v1
kind: Secret
metadata:
    name: tinyauth
    namespace: tinyauth
stringData:
    OAUTH_WHITELIST: ENC[AES256_GCM,data:FPeIGx8sNVAjE5OS3FvH6lXFO6lFMFXONuSjKqFeqCdF5cOGOXB05vN3l9x+QGGEzzJfeY+CcvwO1+UgExgzEXmtAJEdQarTpUKoPogQXg==,iv:/GV2+Zs/XCKe6eJV6SjXF+UB07WC3zYYDrxwMGvDh7U=,tag:ppDbFs2o1VCjD+dh4W03nA==,type:str]
    SECRET: ENC[AES256_GCM,data:VPGtc2RAOJYVMuppsgKEJ1aQVhpud9i+e83KsgxsSMs=,iv:TI5yf9xUpnX9mJQcjfYonlbZMcSpEOWeMxlaIHogduw=,tag:wJm5EL57Y3iuL3Pn5C7e1w==,type:str]
    PROVIDERS_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:1dEcIPwyAiPK0VEJoQGMY4kY2uTc0yg/HHyJRQYOBnMagISejnH/QO2eAklhCThTbr3dVA0uBmwnQgWWlCgmC2sdkl+0aoZw,iv:x3PNKHgmWu4cNmT+KlcRgpUwBGf8AN56HmaVVaZySJo=,tag:U5jFiUZMPsrVFxNzgGeTzA==,type:str]
    PROVIDERS_GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:WcvSGYWa+I6qcn//GWmfeeOtG5EU7gqvrJrJ9NSYmquwttk=,iv:aDra6lgStZtSZpxtik2ydBDHBFCTppg66rL6oXy4LTg=,tag:J1c1DoKVt+N/J/Jd5SyRRg==,type:str]
    PROVIDERS_POCKETID_CLIENT_ID: ENC[AES256_GCM,data:rzLfxv6h1mgdo2J+VdehVuYsMV4NK+WSEzQtYad48v3iJrq0,iv:74MXYJ7slnOEqb/7ELA8nTYAZ85glLQ2eOu0Bt1/1z4=,tag:Cc6Whmsb5EHts7lD/Cozsw==,type:str]
    PROVIDERS_POCKETID_CLIENT_SECRET: ENC[AES256_GCM,data:bj4v+Ry+w0lvsuWvnIh6mc88r6Vi3X+Nqoa9xGj4T9Y=,iv:3z8ElRxMMPM/TRk7QdQXl79HoWEXyeJ2p1d+qPjED2E=,tag:ZTWcN2Qxhd/OgJIoKH67cg==,type:str]
    PROVIDERS_POCKETID_NAME: ENC[AES256_GCM,data:M0A0SNle4dWx,iv:No+BwhzFP9IVsyofhmu14EpxnGQ2uFjL0dFHv96+7/M=,tag:rnlb53Yuc0JjdnsY+TEn/Q==,type:str]
    PROVIDERS_POCKETID_SCOPES: ENC[AES256_GCM,data:hiUBFTZaO9P+EgE6heCfsNOPNFJw4wyV7zXO,iv:C3Qx1G9FQ5L/W4tDac13AvUWgI9OzLqiqhAm3UMAcfI=,tag:bszS/aelKlP0QtgUKNiw9g==,type:str]
    PROVIDERS_POCKETID_AUTH_URL: ENC[AES256_GCM,data:h7BvjAjbnMBtqsbQoPAJOr7/yQHvfbrLcjmZB+reoXYosdekc/mikfwtXy+DubpS+g==,iv:SK3OOmw/9F7c+y/3boinQr1Iq7WWCKvHqRVAVlFxqx4=,tag:54C8k50+3I1MGVu4IiX/Gw==,type:str]
    PROVIDERS_POCKETID_TOKEN_URL: ENC[AES256_GCM,data:TcX9Vtp3YZd+bwMzdYdKvaMxkC1H9Zp6Jdz0WA3DtkpOYZe9o7XbR08L9KD/6q40hnBCqeog,iv:g/+2YzI2hl+KwfzQ0rWt0QHke/Pcxss4cQG6xGkO7x0=,tag:o3qQ/QjNIhABBD69Y1A0xw==,type:str]
    PROVIDERS_POCKETID_USER_INFO_URL: ENC[AES256_GCM,data:tms8jL0T3jZtpSKw5FgFusKnVDca99jEKO7Y0RVrE+y4DM1xlO28IgBeH5T4QUvxGiQuhIfxetjw,iv:rHcKrJ39uFsgOE+qJMcu/eDFNSSqHQm+PYL/IWqL08w=,tag:vN9E0pxpreBI3+plZUsIMQ==,type:str]
    PROVIDERS_POCKETID_REDIRECT_URL: ENC[AES256_GCM,data:TA6dqZm8leo54YdIrj0sz91v+Jy+ingXKqyfDoROg7p0g+qgyLH4f6lkE7qKRCZUblOgPh+TeG0qmc+LhIv1R0Cv,iv:hzlueCZipxYTWwaleTWywLAZjMZwKH5Jde/fIind0sc=,tag:nNWrrlT+meii+idNXPgQGA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T19:24:53Z"
    mac: ENC[AES256_GCM,data:PaT7bjwtpUcAaCT7qe/lfYh3tJui/m7YEMldQw7sTXj1e9INMxNfrQCnZ+3cKcgTMnqsknamlL5lLeFMw+8KpZTe8Q4BvIOPmZhbOmRnTphsXt2Hfl5YsgLBp2Lr2UlqC+TBWJ1v3Qql5vghMza48YUGaWCuMcsUrM2zSUt8FtM=,iv:3p4247JgcNeuO8uB0QCsILJOEW5IgKwBxtIwEKEHqXE=,tag:qrTZnCImW9Gn28R+n1UPXQ==,type:str]
    pgp:
        - created_at: "2026-07-18T19:24:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ifymI7TXLxAQ//eVKeymJQANUAdK4vupJByLDGoKvD73PT1zVzoqYeYlrz
            JJaSt7NaIT8jFrkzYQBw9EmQSrIDXipPJENr6GNR5TwOf7p1oGQsRvHa2Ct0FE5+
            zjKqdy2DWQJNJPUM91eIp6qBqD6Wva4NyvlEr/nK5WK25gWdmWfbpR8M5AgK5Ivb
            3/g+oMP8bbGDc/fyBDEBOTkgMiwFazsen0kqHrft0csB3ScfniwfNKqFBCAP8ZEo
            2/uiJ2N6urGGHDWV0hb45WJ/Ad1cN3d0V1QDdyQAy/pqKnV3XP+QiEXjVs3EdqDq
            hSP29Tw4JJAE2p4chOCX0MqNC0u5F/xHRN2MBrZ3WV1vaLKBxP6z7E09P6xdmI8p
            wHlMyDd8NOwzcl9ZoqyAR121yMTSDX1OVR3SI7F8FORjAMtSE9ilkjlIo87W/PmW
            Cd+uuNCP+K+FJN+FiJ9d1mTUmBJ4S5qfyfckvl5WUzb8UIecDRxN0wsjKPF5YkN+
            edtdt2OSRNzkcw2hrDfucYlPvqefOknQg75u/QSkg8njfVqnVFZuC9rQhGK2wz0C
            YIViBW3/wtGQm1HZYSP2jmTxDJj2vkRJxoUPP5NAGTWKVP7B0m00qgBeMTJseeos
            i1UiC9jv8e0XhDl8L5LjllY031jSE9lecOeCZV5Otbdg7WOtz2vmnaEinb0FvK3S
            XgHKEb20WPtU/jeAKxuGaSFsU05DgjWLkUn0eKXrAhmbCYMVfM2FA56BiuVH+uaI
            IRCWB50lfYupZ2Ny0VV1x4MifGCRjGs23bC5BJTWhTJSXQ7NZZxhR6FGfSDYIig=
            =TmSo
            -----END PGP MESSAGE-----
          fp: E6862079C6D05BFFF38F920C4EB7CEF00A5BE02D
    version: 3.13.2
