endpoints:
  - name: "${APP}"
    group: external
    url: "https://${APP}.hephaestus.markmk.com${GATUS_PATH:=/}"
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == ${GATUS_STATUS_EXTERNAL:=200}"
    alerts:
      - type: discord