apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gatus-namespace.yaml
  - gatus-ingressroute.yaml
  - gatus-rbac.yaml
  - gatus-pvc.yaml
  - gatus-release.yaml

configMapGenerator:
  - name: gatus-configmap
    files:
      - config.yaml=./gatus-config.yaml
generatorOptions:
  disableNameSuffixHash: true