---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-podinfo
  namespace: podinfo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`podinfo.hephaestus.markmk.com`) 
      kind: Rule
      services:
        - name: podinfo
          port: 9898
          namespace: podinfo