apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: omada-controller
resources:
  - omada-controller-namespace.yaml
  - omada-controller-release.yaml
  - omada-controller-ingressroute.yaml
