---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app omada-controller
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      omada-controller:
        containers:
          app:
            image:
              repository: mbentley/omada-controller
              tag: 6.2.10.17
            env:
              - name: TZ
                value: Europe/Copenhagen
              - name: MANAGE_HTTP_PORT
                value: "8088"
              - name: MANAGE_HTTPS_PORT
                value: "8043"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      device-adoption:
        controller: omada-controller
        type: LoadBalancer
        loadBalancerIP: 192.168.20.248
        ports:
          discovery:
            port: 29810
            protocol: UDP
          manager:
            port: 29811
          adopt:
            port: 29812
          upgrade:
            port: 29813
          device-https:
            port: 8043
          portal-https:
            port: 8843
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /opt/tplink/EAPController/data
      work:
        type: emptyDir
        globalMounts:
          - path: /opt/tplink/EAPController/work
      logs:
        type: emptyDir
        globalMounts:
          - path: /opt/tplink/EAPController/logs          