---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app paperless-ngx
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../components/volsync
    - ../../../components/gatus/internal
    - ../../../components/gatus/external
  interval: 1h
  path: ./apps/base/paperless-ngx
  postBuild:
    substitute:
      APP: *app
      SUBDOMAIN: *app
      CAPACITY: 40Gi
      GATUS_PATH: /accounts/login/?next=/
      GATUS_PORT: "8000"
      GATUS_APP: "paperless-ngx-app"
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: &namespace paperless-ngx
  timeout: 5m
  wait: false