apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frigate
resources:
  - frigate-namespace.yaml
  - frigate-release.yaml
  - frigate-ingressroute.yaml
  - frigate-media-pvc.yaml
