apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  chart:
    spec:
      version: ">=2.0.1"
  valuesFrom:
    - kind: ConfigMap
      name: homepage-values