---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app it-tools
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../components/gatus/internal
  interval: 1h
  path: ./apps/base/it-tools
  postBuild:
    substitute:
      HOSTNAME: "it-tools.hephaestus.markmk.com"
      GATUS_PORT: "80"
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: &namespace it-tools
  timeout: 5m
  wait: false