endpoints:
  - name: "${APP}"
    group: base
    url: "https://${GATUS_SUBDOMAIN:=${APP}}.devbu.io${GATUS_PATH:=/}"
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == ${GATUS_STATUS:=200}"