apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app spoolman
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      spoolman:
        containers:
          app:
            image:
              repository: ghcr.io/donkie/spoolman
              tag: 0.22.1
            env:
              - name: TZ
                value: Europe/Copenhagen
              - name: SPOOLMAN_PORT
                value: "8000"
              - name: SPOOLMAN_DIR_DATA
                value: "/data"
              - name: SPOOLMAN_DIR_BACKUPS
                value: "/data/backups"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      app:
        controller: spoolman
        ports:
          http:
            port: &port 80

    persistence:
      files:
        existingClaim: *app
        advancedMounts:
          spoolman:
            app:
              - path: /data


    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
