apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellyseerr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      jellyseerr:
        containers:
          app:
            image:
              repository: docker.io/fallenbagel/jellyseerr
              tag: 2.7.0
            env:
              - name: TZ
                value: Europe/Copenhagen
              - name: PORT
                value: &port 80

    service:
      app:
        controller: jellyseerr
        ports:
          http:
            port: *port

    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /app/config

      tmp:
        type: emptyDir        
