clusterName: hephaestus
talosVersion: v1.13.0
kubernetesVersion: v1.36.0
endpoint: https://192.168.20.190:6443
allowSchedulingOnControlPlanes: true

nodes:
  - hostname: talos01
    ipAddress: 192.168.20.190
    installDisk: /dev/nvme0n1
    controlPlane: true
    disableSearchDomain: true
    nodeLabels: {}
    networkInterfaces:
      - interface: enp0s31f6
        dhcp: true
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/i915
            - siderolabs/intel-ucode

controlPlane:
  patches:
    - |-
      cluster:
        proxy:
          extraArgs: 
            ipvs-strict-arp: "true"
       

          