# yaml-language-server: $schema=https://kube-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: tandoor
  namespace: tandoor
spec:
  sourcePVC: "tandoor-data"
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: tandoor-volsync
    volumeSnapshotClassName: csi-democratic-csi-hostpath
    cacheCapacity: 2Gi
    cacheStorageClassName: democratic-csi-hostpath
    cacheAccessModes: [ReadWriteOnce]
    storageClassName: democratic-csi-hostpath
    accessModes: [ReadWriteOnce]
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 100
      fsGroup: 100
    retain:
      hourly: 24
      daily: 10
      weekly: 5
      monthly: 3