apiVersion: v1
kind: Secret
metadata:
    name: tandoor-volsync
    namespace: tandoor
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:CPkhmeqGcp73mLblRVUEgLCE6g==,iv:51Owr7QICe/TOilY0i6M/wjjHF8e/K9hiU6IWO+DQGE=,tag:ZScZ3a4tdcgMIkSRarcKaQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:gzJGY5BO0sJWPtg=,iv:BJTsj7z07QIEweud3TWoyAEdyk+qY2YBCfRv0TgDpRc=,tag:zmUSoZaOS4uL/iOorlQc4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-31T12:40:40Z"
    mac: ENC[AES256_GCM,data:tlHRKj9huuJKsMQFmeSkXOLVB8f12RqoZo0nuBUT6huzRaPGlmpvEHyTCKuAUozb45Ssb+RJHaWqT0BgYUhjI31ghzQsf0a7BzujSiNsV04GTqgMijxoltmpStbeYENxkU/lK7WaIm51JdQj34PTPm3Nu1pu9c+hBTfCBnbnhOk=,iv:xZuHf3Nw1toIB4tE+Cx9C7y77HNtm4gnTteJrJ5AOIY=,tag:eNBZCYWJgaSyoyBtRvnxsQ==,type:str]
    pgp:
        - created_at: "2025-03-31T12:40:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ifymI7TXLxAQ//ZaeYJVR17RA/dEc0t6pohaXWvjTpTSnGwfRfU559QEtH
            GtW8a8CLTdP0gsYyZutolqABR52KT1PrrVPEEJnLJvYr8ibHNd5lwVAxuf9agsiz
            9dKeqIiqJF4SVz7o3usZgzgaUI8fQwnFs6UN2ZeacWgPDkGPrQcyNwwqZQAJJwyl
            pNffTdbWF4vA7Ka0on6teMRM11K2HbPwrBAOHFuspYmGV+lStpzPAwN0VbC+DHJE
            jzV+wHApgHA+iSLhCoJJGZmSTCq1QfiH0Tc2+c54DADKHGRWYTf7FJL8duAoxy9B
            /K5l9WOhIheenxALiDi7Ai4nFymIfvl2seKZVPbNiCiK1KD9WsGBkK6VAemYVRVF
            y6uLpqKcd4sQWHt+KSeM/lWN+HmgmfiIj+ue9Nud3q8oFfYyMEjf8f2nYvJfx/rH
            1AhkbgDEBGfxaztv49/coGbgoUihAnd7iVtcs17rpO7eueBRIVcG9iS1FON11f8y
            /40Gn8Of92u91levCvp7dfKnPLsgprQoYnU0D4Hr5OuiDUvTA6w4VmzNOfGe/IX4
            /Cltd1NwgdX7j2/71k8+26O+u7QW0JC3fGkwLD9ZEUFD44UVKAlvivoAMkWXejwX
            fJ1fFBnpikIKn7JMwGKGHH20cAuuqVMMvonyFqePxkEZ0ZY+pGHgo44OYwCA4tXS
            XAHi5FEn4QThlmeJAK3n9ELgnGWNAMHlrNWkzhnWTtbaH9MBTfVWXDnDjtuMEpvs
            /NGJo40QvXB23+73yKJsYyKOD6KfBR6xxfE8wCRm3OCraFue9ynSGhctoxSw
            =6jzO
            -----END PGP MESSAGE-----
          fp: E6862079C6D05BFFF38F920C4EB7CEF00A5BE02D
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
