apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - homepage-namespace.yaml
  - homepage-ingressroute.yaml
  - homepage-release.yaml
  - homepage-configmap.yaml
  - homepage-rbac.yaml
generatorOptions:
  disableNameSuffixHash: true