apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  releaseName: homepage
  chart:
    spec:
      chart: homepage
      sourceRef:
        kind: HelmRepository
        name: homepage
  interval: 50m
  install:
    remediation:
      retries: 3