---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: symlinks
  namespace: media
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi           
