apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret-vars
    namespace: flux-system
stringData:
    ALERT_MANAGER_DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:1ZsrdmhADnWFjtm+GdsSW4+mhttg1ucRCNM7aHe+xMCsLbv+r8EbNt69v9Vr1Ff1/bj5Hq2WL97f0oWzBSOWTUHTl4G4CY8Qdo3+v383CI9hy1b38m8g4N33hQk6C5a0dNZY4Or4SVFnOQnH0O9ZC+XbhgngyssCRQ==,iv:4ZzkrDjf8+k0ofRyjT57huYWSCxYctVEPmdXX9jkuiA=,tag:np9WVvSNtYIYoKoQItXsrg==,type:str]
sops:
    lastmodified: "2025-05-16T18:42:51Z"
    mac: ENC[AES256_GCM,data:Dw7Mp+1h38aBr/tkzH83abaokW7B3tRXSAnHkZdA81TUw2+FV14B5g2Gv7/VUk0nYWjF/uRy4S7FWB5B8xgiIm+jZGiasIZWO7SXf27/zKwq6c/byt9xthXIjKSghJbwzBDLy4ArJuf9V5kDtIBHkLF2vmbJDfqTnoLAmz8cugI=,iv:vkooTWFo9pQDbKBcBxBY4QL91wb54y4tZzSZhFULg/E=,tag:TK2F1DvaPjeu1oZ/kuODtA==,type:str]
    pgp:
        - created_at: "2025-05-16T18:42:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ifymI7TXLxAQ/+Kok+me5tZwAD289zU7Shn2XdEtDqc15+DYSZ5I2iVo6+
            DWtEfrKFITnvd7CE8HWISb5yBji1LujDPmWTKt6z0RUeB+WMOTTMijH3yscK2mkA
            JyNS+oS5RHHJPgw3QCEvzO6rMMY3GaUtc9tgcYBrHZ3xNzz6SkDevOf+iVZQAuoP
            rf/td7vkZk2rvf2PCMq0WAcw6P4a39ARO+1scBS1Bza2CBBNohPMfS1Fqkh/FuZ0
            Jo/wj3Vqb6NvHE/9d7OS+r6Z8CEjJglFfn5kIIf2rs92ntnNy4czz/fkC4HnMRox
            reuhNdQvQYwrttun9RkinNF6gnC2PGq8Izb0uRmTdXojZdGJTtQC1JhJMJdUctBd
            h134jhjNptC5ZLg/p8Mxl5Yd9X/bS3Z5iQ5Ump4poOTIOQxdUJ4rOON4vPJAzChn
            qXEfxe23W1rnpDZoXs8kr6ZF8YhE/fQU7O5g1+d8ErAauEdxQAaFACdIHimr/Rds
            SdgsEbWredZ0fs+Rtd9eKSDu/l+QtRtQyoBBad3KyGKvGFByw3nJWosFF70JXRNF
            bz1Uz683wQbMM3DSWRqWF75bTuMcMJCl679xeU1cdroYDOsEdw71YGT62kxD2tGF
            VA8fRr4XEV/vdDZWZFlg37HZhqu8wtrVWRvYDX4rNWawXQl73yrVRQAmWPcBeuvS
            XgF2TIjBvQ4+qsJ8jpg0ZkuhHREuBbciH0GEVnlxQLl3lEQR5JPFQ0cysFpkZoqy
            0fOeNSTY/rcmxxJ7Gp8TRrD6w5PMdzPMcm0k0fs5kW5ZvHvhc1Cy59M388a75+w=
            =5DDx
            -----END PGP MESSAGE-----
          fp: E6862079C6D05BFFF38F920C4EB7CEF00A5BE02D
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
