apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app omni-tools
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      omni-tools:
        containers:
          app:
            image:
              repository: iib0011/omni-tools
              tag: 0.3.0

    service:
      app:
        controller: omni-tools
        ports:
          http:
            port: &port 80
