apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
  - home-assistant-namespace.yaml
  - home-assistant-ingressroute.yaml
  - home-assistant-release.yaml
