apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellyfin
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      jellyfin:
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.2
            env:
              - name: TZ
                value: Europe/Copenhagen

    service:
      app:
        controller: jellyfin
        ports:
          http:
            port: &port 8096

    persistence:
      config:
        existingClaim: *app
        advancedMounts:
          jellyfin:
            app:
              - path: /config  
      
      media:
        existingClaim: shared-media-pvc
        advancedMounts:
          jellyfin:
            app:
              - path: /mnt/library         

      rclone:
        type: hostPath
        hostPath: /mnt/zurg/
        globalMounts:
          - path: /mnt/zurg
            readOnly: true

      tmp:
        type: emptyDir
        advancedMounts:
          jellyfin:
            app:
              - path: /cache
                subPath: cache
              - path: /transcode
                subPath: transcode        
