apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app grocy
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          app:
            image:
              repository: linuxserver/grocy
              tag:  4.5.0
            env:
              - name: TZ
                value: Europe/Copenhagen
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 9283

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /config
