apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kitchenowl
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      kitchenowl:
        containers:
          app:
            image:
              repository: tombursch/kitchenowl:latest
              tag: v0.7.4
            env:
              TZ: "Europe/Copenhagen"
              STORAGE_PATH: "/data"
              OPEN_REGISTRATION: false
              DISABLE_USERNAME_PASSWORD_LOGIN: true
              FRONT_URL: https://kitchenowl.hephaestus.markmk.com
            envFrom:
            - secretRef:
                name: kitchenowl-secret

    service:
      app:
        controller: kitchenowl
        ports:
          http:
            port: &port 8080

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          kitchenowl:
            app:
              - path: /data
