apiVersion: apps/v1
kind: Deployment
metadata:
  name: zurg
  namespace: zurg
  labels:
    app: zurg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zurg
  template:
    metadata:
      labels:
        app: zurg
    spec:  
      initContainers:
        - name: merge-config
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Merging config files..."
              cat /zurgsecret/secret.yml > /config/config.yml
              cat /zurgconfig/config.yml >> /config/config.yml
          volumeMounts:
            - name: zurg-config
              mountPath: /zurgconfig
            - name: zurg-secret
              mountPath: /zurgsecret
            - name: merged-config
              mountPath: /config      
      containers:
      - name: zurg
        image: ghcr.io/debridmediamanager/zurg-testing:latest
        volumeMounts:
        - name: merged-config
          subPath: config.yml
          mountPath: /app/config.yml
      volumes:
      - name: zurg-config
        configMap:
          name: zurg-config
      - name: zurg-secret
        secret:
          secretName: zurg-secret          
      - name: merged-config
        emptyDir: {}
      restartPolicy: Always
