apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: spoolman-ingressroute
  namespace: spoolman
  annotations:
    gethomepage.dev/href: "https://spoolman.hephlab.duckdns.org"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Spoolman"
    gethomepage.dev/description: "Application for managing filament spools."
    gethomepage.dev/app: spoolman
    gethomepage.dev/group: "Tools"
    gethomepage.dev/icon: "https://raw.githubusercontent.com/Donkie/Spoolman/cd274a9968af26eae5c14a28d6a8c9ae61fccb7a/client/icons/spoolman.svg"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`spoolman.hephlab.duckdns.org`)
      kind: Rule
      services:
        - name: spoolman
          port: 80
      middlewares:
        - name: websocket-headers
        - name: enforce-http1
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: enforce-http1
  namespace: spoolman
spec:
  headers:
    customRequestHeaders:
      Connection: "keep-alive"  # Force HTTP/1.1 behavior
    customResponseHeaders:
      Connection: "keep-alive"  # Ensure HTTP/1.1 response
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: websocket-headers
  namespace: spoolman
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
    customResponseHeaders:
      Connection: "Upgrade"
      Upgrade: "websocket"      