---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex-ingress
  namespace: plex
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`plex.hephlab.duckdns.org`) 
      kind: Rule
      services:
        - name: plex-service
          port: 32400
          namespace: plex