---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex-ingress
  namespace: plex
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`plex.hephaestus.markmk.com`) 
      kind: Rule
      services:
        - name: plex
          port: 32400
          namespace: plex