apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app babybuddy
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      babybuddy:
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/babybuddy
              tag: 2.7.1
            env:
              - name: TZ
                value: Europe/Copenhagen
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

    service:
      app:
        controller: babybuddy
        ports:
          http:
            port: &port 3000

    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /config