apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: babybuddy
  namespace: babybuddy
  annotations:
    gethomepage.dev/href: "https://babybuddy.hephaestus.markmk.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Baby Buddy"
    gethomepage.dev/description: "Application for tracking baby care activities."
    gethomepage.dev/app: babybuddy
    gethomepage.dev/group: "Tools"
    gethomepage.dev/icon: "https://cdn.jsdelivr.net/gh/selfhst/icons/svg/baby-buddy.svg"
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`babybuddy.hephaestus.markmk.com`)
      kind: Rule
      services:
        - name: babybuddy
          port: 8000
