apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: babybuddy-pvc
  namespace: babybuddy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path