apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cura
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      cura:
        containers:
          app:
            securityContext:
              allowPrivilegeEscalation: false
            image:
              repository: lscr.io/linuxserver/cura
              tag: "5.11.0"
            env:
              TZ: "Europe/Copenhagen"
              PUID: "1000"
              PGID: "1000"
              UMASK: "022"
            envFrom: 
            - secretRef:
                name: cura-secret 
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 4Gi                

    service:
      app:
        controller: cura
        ports:
          http:
            port: &port 3000

    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          cura:
            app:
              - path: /config
