apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pocket-id
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pocket-id.hephaestus.markmk.com`) 
      kind: Rule
      services:
        - name: pocket-id
          port: 1411
          namespace: pocket-id