apiVersion: v1
kind: Secret
metadata:
    name: pocket-id
    namespace: pocket-id
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:Dnu4g6lOpAvUkn1/eqLY2oJ3jH30yQUNO8pH8c7BjsZEXlf52dHNwiSYq5I=,iv:nIpDNdZvsvTh/XV7nBufSO6bCo70Vn2q9HKE3YibAQ4=,tag:phKCSRY8WrfCNhHO3pSgiQ==,type:str]
sops:
    lastmodified: "2026-04-19T07:15:22Z"
    mac: ENC[AES256_GCM,data:alqlP3rFZv3NYQW1oKz56WV6VHeN/lfI8PShA83zmDnShNa3LWeAAcMbCZJndlRJRrRytrn0IVlq0Ss3FCdZWYPwaST6Cio/QFo10w/HlzCzh/9Urqz0jTldKmiBlw5VZs7KGSNWNRmI6aDzXyNH+p8f1291MPYbT3UbdgM1RtQ=,iv:JgLlDGrW0dh4gGavg6nZxib8YVxEzvQcPf4/ZQ3vL9w=,tag:fE6UUecJbjBv654nXZ7zPQ==,type:str]
    pgp:
        - created_at: "2026-04-19T07:15:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ifymI7TXLxARAAr0HCOnxbss+ZSty8KuZYIxV0DsaHmKvu51wM7glPdyj2
            1rtKZm4VQFgb+5oPJOq7kB1mZMSFC/BgtzbAsxpFqy5BUAS6/6P2IPp49QMXf3Fj
            EwTaswVV0+HzieWGApVjPQftoelqrQJ8XaOlCKn9XPbPL04MfTCAEzWgcU5IcmY5
            nAdLQytveo2ByTfHPteqeHQsv3snDxZwhYVxRGwadobKlptA6iuxD+Fid/5kMPOC
            jYWnDY5+AOj33F2y1/gjzqh+Oq5i0aSPfOAFwKzsSVqL4NCukpOrpXANJLKKonuW
            VA1y74Dlcai7xRwV67ycm97gMapo2vLddn12GMtH/Pa22i/+jTzRLb5KHQx7x2o6
            NE3/K1bA15jkXgOGMsS+1WefZYL4TtE+gN9ctCWjjybbAl7AfXQh7Zi2pve4MoY+
            5mlWloZrR45jUk0gpbqwm+HxXRHnjnZsMXRF/Ny4VCWvNJ/BaAlvbsdy7qLNwz2c
            deEcGI4w3GCnD/YdNT+c+L5k1nisvf0v2ZHTrGXIoENhQlEWLAq7PFlw2E4e7gmd
            0ouNhCirsDY7RIKsWjLD4Fq+h9oJK9hXkEiv9CDCX42UKpkr/KfA3TwXL05CkImN
            KTiqxNG6QRQf1u833w0MszLu/GHHZJ+j8kxGk5oXa6Bv29gUqAl1E9hccyJcSILS
            XgEfTCLktPSQ9Q+uA0s6yNrBElnOUszew/p16+c3k3GB3OWPF88SEqhXtKIr/sH0
            ERFjwV4J0X9x5ZmLt46CQZQQAwRnistuOgjtq/rhce660PzgxiaJQCJbM0WyNQY=
            =62UC
            -----END PGP MESSAGE-----
          fp: E6862079C6D05BFFF38F920C4EB7CEF00A5BE02D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
