apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
  namespace: volsync-system
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: volsync
    namespace: volsync-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    manageCRDs: true
    replicaCount: 1
    metrics:
      disableAuth: true
  targetNamespace: volsync-system