apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
        app.kubernetes.io/name: plex      
    spec:
      containers:
        - name: plex
          image: plexinc/pms-docker@sha256:a13f35ef4719603e65ce867df9056bf7f99993510b64aa7f91e94e4741482870            
          # envFrom:
          # - secretRef:
          #     name: plex-secret
          volumeMounts:
            - name: shared-data
              mountPath: /mnt/library
              readOnly: true
            - name: plex-config
              mountPath: /config    
            - name: rclone-data
              mountPath: /mnt/zurg                          
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-media-pvc
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-pvc
        - name: rclone-data
          hostPath:
            path: /mnt/zurg                           
 